DS-Homebrew/TWiLightMenu

titleandsettings/nitrofiles/languages/italian.ini
I also noticed that actually the app doesn't support all the accented letters, so even if the texts are correct, they are not correctly shown, and some of the descriptions don't match.
_Tell us what's new._
_Tell us what's fixed._
*** 
=> Italian translation

titleandsettings/nitrofiles/languages/italian.ini
Translated new lines.
Slight improvements in the existing localization.
Not tested.
*** 
=> Italian translation improvements

README.md
for arch at least, unsure about other os's but i imagine they need the same changes. and both the .a and .h file are required.
*** 
=> fix compilation errors

titleandsettings/nitrofiles/languages/italian.ini
=> Updated italian strings

titleandsettings/nitrofiles/languages/spanish.ini
_Some tweaks have been made, and Mac-like string has been translated, also some corrections and missing words have been added._
_Can't test, but I hope that the tweaks work._
*** 
=> Some tweaks and translated "Mac-like" string

titleandsettings/nitrofiles/languages/spanish.ini
_Did some corrections, and, a new thing, added strings from the language.cpp, thanks to that, English text now will be in spanish._
_Can't test._
*** 
=> New strings added based on the language.cpp

titleandsettings/nitrofiles/languages/spanish.ini
_Fixed a derp string, ("SEL_AK:" to "SEL_AK = "), and adjusted "the DESCRIPTION_S1SDACCESS" string. Deleted useless strings._
*** 
=> Derp fixes

romsel_aktheme/arm9/source/common/systemdetails.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/Makefile, rungame/arm9/source/main.cpp, titleandsettings/arm9/source/common/systemdetails.cpp, titleandsettings/arm9/source/main.cpp
All I've changed is a few grammatical typos. No code has been touched.
I have not, but I have not touched the code!
*** 
=> Correct grammatical error "ran -> run"

titleandsettings/nitrofiles/languages/french.ini
Just updated the french language from titleandsettings, because it wasn't really good, and even hardly understandable sometimes. I may have misspelled one or two thing, but everything should be understandable now ^^
Tested it with HiyaCFW on my DSi.
*** 
=> Updated French language to be more accurate

titleandsettings/nitrofiles/languages/french.ini
I just updated the french language in titleandsettings, to add 2 translation that was forgotten in my last PR, and fixed some bugs while displaying text, because I used accentuated characters in some translation, forgetting I couldn't use them.
On my DSi with hiyaCFW
*** 
=> updating french language

rungame/Makefile
Changed Robz8 ----> RocketRobz
_Changed Robz8 name author to RocketRobz. No code touched._
=> Changed author name

titleandsettings/nitrofiles/languages/french.ini
Just updated the french language of the settings application to add the new sysnand parameters added in the latest version.
Also changed Blue moon to Lune bleue in the 13th r4 theme, as well as other few little changes still in the french language.
On my DSi with Hiyacfw, unlaunch 1.7, and the latest version of TWiLightMenu++ ^^
*** 
=> Updating french language with the new sysnand parameters added in latest version

README.md
Fix Vulpes-Vulpeos’s credits a bit
=> Fix for Vulpes-Vulpeos

settings/nitrofiles/languages/spanish.ini
_Added the SCFG translated, as well the description._
*** 
=> Added SCFG translate

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
These were supposed to be in #338, but I forgot to actually push the last 2 commits 😅 
DSi (J) w/ latest TWLMenu / Hiya / Unlaunch
*** 
=> DSi/3DS/R4 themes: Add SNES emulator choosing (I forgot to push these commits...)

settings/arm9/source/bootstrapsettings.h, settings/arm9/source/main.cpp
I've added support for my "R4-Like" loading screen
new 3DS 
*** 
=> Add support for my "R4-Like" loading screen for nds-bootstrap

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- To be a bit more like the original DSi menu, this makes it so that the top screen is randomly chosen from several pictures
- It will randomly load any `.bmp` file in `sd:/_nds/TWiLightMenu/dsimenu/photos/`
- It does not load files that start with `._` (Apple's index files)
DSi (J) with the latest Hiya/TWiLight/Unlaunch
*** 
=> DSi theme: Make the top scrren picture be randomized

README.md
=> Add links to as many Github profiles as I could find

settings/nitrofiles/languages/spanish.ini
_Reading the new extended ASCII characters on the specified PR above, I made the same thing with the spanish language._
*** 
=> Added support followed on PR #376

README.md
add more URLs to the readme.md file, and add a few more credits (specifically for Epicpkmn11)
=> add more URLs

.travis.yml
I just realized I forgot to push this to TWiLight, this'll make the the Travis builds push to [the TWLBot repo](https://github.com/TWLBot/Builds) properly
On my alt account's fork's master branch
*** 
=> Fix Travis pushing builds

.travis.yml
It should finally actually be fixed 🤞 
No where ;P
*** 
=> Actually fix Travis this time

romsel_aktheme/nitrofiles/language/lang_cn/language.txt, romsel_aktheme/nitrofiles/language/language.ini
the Chinese language.txt updated&BTW edited the language.ini
=> Update the Chinese language.txt for akmenu 

romsel_aktheme/arm9/source/language.h
This PR has been tested using latest devkitPro, devkitARM and tested on DSi Console
=> Edited fot the Chineses language.txt change

README.md
This just puts Travis' build passing/failing indicator at the top of the README, if you want to move it you can but I think it's probably good to have it there
It shows correctly on this fork I'm PRing
*** 
=> Add Travis' build passing/failing to the README

settings/nitrofiles/languages/spanish.ini
_Added new translations of new version. Code untouched._
*** 
=> Translated strings

.travis.yml, docker/Dockerfile, romsel_aktheme/arm9/source/common/files.cpp, romsel_aktheme/arm9/source/dsrom.h, romsel_aktheme/arm9/source/ui/button.cpp, romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_dsimenutheme/arm9/source/date.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/date.cpp, settings/arm9/source/.vscode/settings.json, settings/arm9/source/settingsgui.cpp, settings/arm9/source/settingsgui.h, settings/arm9/source/settingspage.h, settings/compile_docker.ps1
* Fix the bug where akmenu would not show all entires in a folder
* Fix some GCC warnings in dsimenu and r4menu due to returning local addresses in `date.cpp`
* Fix GCC warnings in settings
* Update the dockerfile to use the latest devkitARM release with patched libnds
Nintendo DSi
*** 
=> Various bug and warning fixes

settings/arm9/source/settingspage.h
Fixed a compile error at settingspage.h. Oddly enough it compiled on my version of dkA :/
*** 
=> Fix compile error

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
Tested on DSi console with both DSi/3DS theme.
It seems a little better than before.
=> changed it to avoid the icons show with 3DS theme

settings/arm9/source/main.cpp
added the ability to choose the random theme setting (NightYoshi370 might've forgotten) and clean a bit of code up
white n3ds small w/ 128GB SD Card
(also wait for Travis CI to attempt to build it)
*** 
=> add ability to *choose* "Random" theme and clean code a bit

7zfile/_nds/TWiLightMenu/dsimenu/themes/green/theme.ini, 7zfile/_nds/TWiLightMenu/dsimenu/themes/white/theme.ini, 7zfile/_nds/TWiLightMenu/dsimenu/themes/yellow/theme.ini
Forgot to copy these INIs over correctly to 7zfile from #459. Sorry :|
*** 
=> DSi Themes: Fix Theme Inis

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.h, romsel_dsimenutheme/arm9/source/graphics/color.h
* Improved alpha blending algorithm to work better with XBGR1555
* Picked new palette indices to look better when drawn
* Blend multiple times with the background before drawing
* Heuristic to select palette colors based on lightness of background
* Nintendo DSi
* Nintendo DS Lite
*** 
=> DSi/3DS Theme: Greatly improve the appearance of the profile name

romsel_dsimenutheme/resources/dsimenu_theme_examples/theming.md
Updates the theming guide in in accordance with #476
=> Update Theming Guide

README.md
i've made the readme a bit nicer, take a look!
=> make the readme a bit nicer and touch ups

.travis.yml
All deployments are now handled by Azure Pipelines.
=> Comment out Travis deploy

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/game-issue.md
- This adds more issue templates:
- Feature request issue template (it's just default)
- Bug report (it's the same as before)
- Game issue (hopefully a strong enough warning that people go over to nds-bootstrap's repo)
https://github.com/Epicpkmn11/HBChecker/issues/new/choose (I'll change if back once this is Merged / Closed if you want to do the templates differently)
*** 
=> Add more issue templates

romsel_dsimenutheme/arm9/source/sound.cpp
derp fix for loading custom soundbanks
=> sound bugfixes

.github/PULL_REQUEST_TEMPLATE.md
- This removes the never used bottom lines from the PR template:
```
```
n/a
*** 
(n/a)
=> Clean up the PR template

settings/nitrofiles/languages/french.ini
I just updated the french translation, and added accentuation to it
on my cfw DSi(hiya) and New 3DS (luma) on the latest version each
*** 
I also noticed I have nothing for the FAST, or SLOW word, and the theme name are in english now too, I think I might have to translate it in their respective theme files ?
=> updating translation and adding accentuation to it

settings/nitrofiles/languages/portuguese.ini
Based on the latest updates to the english.ini file, this translation was updated accordingly.
> Small typos and grammatical errors fixed as well.
> Included some "text-wrapping" to accomodate the display size.
=> Updated portuguese.ini file

README.md
Only the README.md
I have compiled it with no errors on dkP + dkARM 2.10.0, and the Azure icon now shows the correct build state.
***
=> Fix Azure Pipelines link due to recent repo change

settings/nitrofiles/languages/italian.ini
The Italian translation wasn't being updated for a while now, so I translated the missing strings and fixed some typos/text overlaps. Compiled and tested without issues.
=> Updated italian.ini

mainmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
i added 3 Yugioh games to the SBE list
DSi XL on Hiya 1.3.2 Unlaunch 1.9
***
=> add 3 games to speed bump exclude list

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.cpp
- This add proper folder handling to the cheat menus for the DSi/3DS/R4 themes which fixes the Guru Meditation Errors for me
- (Fixes #368)
DSi (J) with the latest TWiLight / Unlaunch.
***
=> DSi/3DS/R4 Themes: Fix cheat menu stability

azure-pipelines.yml
- This (should) make the TWLBot commits have the correct commit sha
- This means I should be able to show commit notes in the Updater
No where, I can't really...
***
=> Use correct commit sha in TWLBot commit (Hopefully)

azure-pipelines.yml
This fixes the Azure release not having the commit tag and message
On my fork, https://github.com/TWLBot/Builds/releases/tag/v20190722-045510
***
=> Fix Azure's release

mainmenu/arm9/source/graphics/graphics.cpp, mainmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/source/main.cpp
*To be written at a time that isn't 12:30 AM.*
But basically, just port over some missing R4 features and cleanup the codebase
I have not tested this. I'l looking for testers though.
***
=> WIP Code cleanup

romsel_dsimenutheme/arm9/source/main.cpp, rungame/arm9/source/main.cpp
- Changes indentation to not look as if it was made for a smartphone in the DSi Theme
- Use switch cases in rungame (saving about 10 lines)
This has no effect on the user experience. Only on the backend
***
=> [Minor PR] Indentation changes and usage of switch cases

settings/arm9/source/language.cpp
Just removed some unused strings
They're unused so they don't need to be tested
***
=> [SETTINGS] Removed unused language strings from language.cpp

settings/arm9/Makefile
- This simply changes the git command used to a different one that doesn't give an error if no tags were found
On my MacBook
***
=> Use a different git command to get check for a tag

azure-pipelines.yml
- This should make it not delete `Themes.7z`
- Sorry for doing another PR right after the last one but I didn't think to do this ;P
***
=> This should make it not delete `Themes.7z`

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/main.cpp
- This makes the DSi/3DS fades much faster and makes the DSi theme only do the app drop in once
DSi (K) with the latest TWiLight / Unlaunch
***
=> Speed up fades and only do app drop in once

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp
- This makes hiding use the FAT attribute instead of a leading `.` so that files / folders with specific names can still be hidden
- Leading `.`'s will still cause files to be hidden, but the FAT attribute will be used if it is unhidden and rehidden
DSi (K) with the latest TWiLight & Unlaunch
***
=> Hide using FAT attribute instead of leading .

7zfile/_nds/TWiLightMenu/akmenu/themes/Adv.EvoI/uisettings.ini, 7zfile/_nds/TWiLightMenu/akmenu/themes/HatsuneMiku/uisettings.ini, 7zfile/_nds/TWiLightMenu/akmenu/themes/gbatemp.v1/uisettings.ini, romsel_aktheme/arm9/source/dsrom.cpp, romsel_aktheme/nitrofiles/language/lang_cn/language.txt, romsel_aktheme/nitrofiles/themes/zelda/uisettings.ini
_The Text is based on #894._
_I think any used string in akmenu should be translated with this._
_Also made the translated START button text read from the language file on all needed themes of akmenu._
_DSi(Chinese) with the latest TWiLight and Unlaunch_
*** 
- [√ ]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.
=> Update Chinese translation (akmenu)

quickmenu/arm9/source/main.cpp
_Fix the DLP path for CHN and/or KOR console._
_I tested it on my CHN console._
*** 
- [√ ]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.
=> Ues correct DLP path for CHN and KOR

quickmenu/arm9/source/iconTitle.cpp, romsel_aktheme/arm9/source/common/fixedbanners.h, romsel_aktheme/arm9/source/language.h, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_aktheme/nitrofiles/language/lang_cn/language.txt, romsel_aktheme/nitrofiles/language/lang_de/language.txt, romsel_aktheme/nitrofiles/language/lang_en/language.txt, romsel_aktheme/nitrofiles/language/lang_es/language.txt, romsel_aktheme/nitrofiles/language/lang_fr/language.txt, romsel_aktheme/nitrofiles/language/lang_it/language.txt, romsel_aktheme/nitrofiles/language/lang_jp/language.txt, romsel_aktheme/nitrofiles/language/lang_ko/language.txt, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/iconTitle.cpp
_It is to Simplify CRC check for fixedbanner._
_This will made fixedbanner works fine on romhacks and/or translation roms._
_I tested it on my DSi console._
*** 
- [√ ]  This PR has been tested using the provided devkitPro, devkitARM, and EasyGL2D.
=> Simplify CRC check for fixedbanner

title/arm9/source/bootsplash.cpp, title/arm9/source/common/dsimenusettings.cpp
_Now read system language for h&s screen on chn/kow console._
_Also use twlCfg for getGuiLanguage._
_Tested on my chn console._
*** 
=> title: Bug Fix

quickmenu/arm9/source/date.cpp
_Fix time text on bottom screen for DS Classic Menu._
_Tested on DSi console._
*** 
=> DS Classic Menu: Fix time text

quickmenu/arm7/source/main.c, quickmenu/arm9/source/nand/f_xy.c, quickmenu/arm9/source/nand/f_xy.h, quickmenu/arm9/source/nand/nandio.c
_Port from GodMode9i 65394c3._
_I tested it on my DSi console._
*** 
=> Get ConsoleID without reading from 0x4004D00 for nand access

settings/nitrofiles/languages/german.ini
I updated some translations
***
=> Updated german.ini

romsel_aktheme/nitrofiles/language/lang_de/language.txt
I updated some translation.
***
=> Updated german translation

settings/arm9/source/language.inl
Fixes #1022
Just a string
line side to size
It's just changing the string being printed on the screen, no methods are changed.
*** 
This PR doesn't change the way code runs, just what it prints, so testing isn't neccesary here.
=> Fixed a typo size - instead of side

crowdin.yml
I'll set up Crowdin to use my fork to prevent its commit spam on Discord, but this config needs to be in upstream so that I can keep my master branch clean
N/A
***
=> Add Crowdin configuration file

azure-pipelines.yml
1. In the azure pipelines, we currently hardcode Ubuntu 20.04. This should make it automatically use the latest ubuntu
2. Also, specify to update p7zip and the others. Hopefully this would also fix the TWiLight Menu++ Updater bug
This is an azure thing. Can't really test it
*** 
What version of devKitARM and libNds you use doesn't matter IIRC
=> Always use recommended ubuntu and specify updates to libraries

azure-pipelines.yml
Pacman's removed from Azure due to a request by WinterMute in another issue.
It's an azure thing, can't be tested
***
=> Remove Pacman from CI

.github/workflows/nightly.yml, .github/workflows/release.yml, manual/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/settingsgui.cpp
- This fixes crashing when trying to print off screen
- Was causing guru errors in settings in German and Polish
- Also makes DSi 7z's have the contents of "SDNAND root" in the root, instead of that folder still existing
- Also fixes the SELECT Menu crashing on DS Phat/Lite when in German
- DSi (K) from Unlaunch and DSTT
***
=> Don't print off screen and other bug fixes

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.h
- Fixes #724 
- Also just rewrites the cheat folder handling a little bit to be a bit more efficient
- DSi LL (J) with the latest Unlaunch
***
=> DSi/R4: Fix one per folder cheat selection

crowdin.yml
- Sorry, I accidentally messed it up in #1146 😅 
- N/A
***
=> Fix crowdin.yml

booter/Makefile
- This is just 8da82d4637123da0bded3564db34987f3af05f69 git cherry-pick'ed into its own PR ;P
- Fixes #1139 
- Should this be added to the other srldrs too?
***
=> Restore animated title

.github/workflows/nightly.yml
- Whoops, I copy pasted this from release to nightly and forgot to check it...
- https://github.com/Epicpkmn11/TWiLightMenu/actions/runs/214058650
***
=> Fix trying to delete the release debug in nightly

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.cpp
- Fixes #1168 
- DSi (K) with the latest Unlaunch
***
=> Fix deselecting cheats in one cheat folders

.github/ISSUE_TEMPLATE/config.yml
- Just fixes some outdated info about the Discord server (also rewords things slightly)
- N/A
***
=> Update issue template config.yml

README.md
- This simply adds a translating section to the README to make it more clear that translations should be done on Crowdin
- https://github.com/Epicpkmn11/TWiLightMenu/tree/add-translating-to-readme#translating
***
=> Add translating section to README

quickmenu/arm9/source/main.cpp, title/arm7/source/main.c, title/arm9/source/main.cpp
Attempts to disable Slot 1 power when running under DSi mode with SCFG
DSi XL with DSTWO
***
=> Slot 1 power saving

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- Fixes #1276 (the hanging part is already covered by another issue)
- DSi (K) from internal SD and Acekard 2i
***
=> Don't reopen SELECT menu when closed with SELECT

manual/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.cpp
Was in a bit of a rush and didn't test #1333 all that well and whoops while it did fix the problem, it broke numbers in other places 😅 
This properly fixes them so they should work everywhere.
("2rGBARunne")
- DSi (K) from internal SD and DSTT
***
=> Properly fix bidi numbers

manual/arm9/source/main.cpp
- Finally got around to making the links in the manual actually be generated, but the checked positions are currently off, so this fixes that
- no$gba
***
=> Fix links in the manual

.gitignore, settings/arm9/Makefile, settings/arm9/source/settingsgui.cpp
Also:
- Switch to "version.h" with define instead of -D define so that it rebuilds on committing
- Change to first 7 of the hash instead of 8 to match GitHub
- no$gba
***
=> Make nightly version number include tag

.github/workflows/nightly.yml
- #1384 while it did make the TWLBot commits have message, it's rather broken the messages weren't escaped so `*` would list the directory and such and on Discord they were rather broken too, so this time it should actually be good
- I did some tests on a separate branch, but deleted the releases as I was skipping the TWiLight build to save time, it *should* be good though
***
=> Actually fix commit messages

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- Helps if translations are longer / shorter than English
- no$gba
***
=> Automatically vertically center can't launch text

quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/ndsheaderbanner.cpp, romsel_r4theme/arm9/source/main.cpp, romsel_r4theme/arm9/source/ndsheaderbanner.cpp
Fixes the old patches having priority if you just didn't delete them, this should only be used for ones not in the pck for testing new ones and such.
***
=> Look for APfix & widescreen files in the extras folder

Makefile, manual/Makefile, manual/arm9/source/graphics/gif.hpp
_Fix compilation error._
_No$GBA with the dist 'manual.nds'._
***
- [√] This PR has been tested using the latest version of devkitARM and libnds.
=> Fix compilation error for manual

README.md
I've added a few user links to the widescreen cheats credits, with a couple of other adjustments.
No need to test.
***
=> README user links

.github/workflows/nightly.yml
- Uploads the apfix.pck file to TWLBot/Builds's extras folder
- Tested the command on my computer, haven't tested the Actions though
***
=> Upload apfix.pck to TWLBot

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.h, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.h, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/iconTitle.h, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/ndsheaderbanner.cpp, romsel_dsimenutheme/arm9/source/ndsheaderbanner.h, romsel_dsimenutheme/arm9/source/perGameSettings.cpp
- Oh god I used to be terrible at coding lol
- Improves my old touch code and several other janky bits of my old code
- The dragging is still a little weird, but other than that it's basically perfect to the official menu now
- Also adds tapping on the icons on either side to move to them
- Makes the scrolling smoother
- Also a couple, but I mainly focussed on my bad old code in this
- Fixes the colon drawing causing a bit of stuttering, couldn't tell before but it was really clear with the smoother scrolling, and also just makes that whole code be less of a complete mess lol
- Changes `extention()` to `extension()` and makes it take a vector
- Cleans up the iconTitle.cpp code a bit
- Draft because I need to test it better, if y'all can test let me know if I broke anything
- Fixes #1494
- …
=> Improve touch and scrolling

universal/include/twlClockExcludeMap.h
add LEGO Batman to the twlClockExclusion list
NH Homebrew server. Flickering top/bottom screens. standard issue with these games
***
=> add LEGO Batman to the twlClockExclusion list

romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp
=> Show * next to existing save numbers

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/language.inl, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.h, romsel_dsimenutheme/nitrofiles/languages/en/language.ini, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/main.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/perGameSettings.h
- Closes #1729 
- DSi (K) from DSTT
***
=> Add use nds-bootstrap to per-game settings

title/arm9/source/main.cpp
- Makes it automatically detect the SysNAND region and launcher app from NAND on DSi
- Settings are still left in because the region seems to be used on 3DS sometimes and it can't be detected there and you may want to switch the launcher app if you use DSi Language Patcher or update
- DSi (J) from Memory Pit
***
=> Autodetect Launcher App & SysNAND Region from NAND

settings/arm9/source/main.cpp
There were multiple if statements right next to eachother containing the same conditions. I grouped them and placed them with tabs.
No test needed imo, but best to look over
***
- N/A This PR has been tested using the latest version of devkitARM and libnds.
=> Cleanup of if-statements

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp
- Checks the internal libfat state instead of running `FAT_getAttr()` to check for hidden files since we already have that data, just not supposed to be looking at it
- This speeds up the hidden file check immensely, ~2 seconds to load an ~1.3k item folder on the R4 theme vs over a minute (so long I gave up waiting) before
- This code is also *extremely* cursed and disgusting and I hate it so much, but it works so who am I to judge
- Also changes the 320 file limit to be 320 *games or folders* (valid items) not 320 total items, the speed difference is negligible even with thousands of items
- Edit: Oh, also fixes a warning in the `displayNowLoading()` function, I think I did that right
***
=> DSi/R4 themes: Speed up hidden file check

romsel_dsimenutheme/arm9/source/sound.cpp
- Fixes converted ADPCM skin music playing at the wrong speed if it isn't 16kHz mono
***
=> Use WAV header for converted ADPCM

romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.h, romsel_dsimenutheme/arm9/source/graphics/color.h
- makes alpha blending the top screen text optional
- untested
***
=> Add option to disable alpha blending

booter/arm9/source/main.cpp, gbapatcher/bootloader/source/fat.c, imageview/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.cpp, quickmenu/arm9/source/graphics/FontGraphic.cpp, quickmenu/arm9/source/main.cpp, quickmenu/arm9/source/nand/sector0.c, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/sound.cpp, romsel_dsimenutheme/arm9/source/tool/adpcm-xq.c, romsel_r4theme/arm9/source/graphics/FontGraphic.cpp, romsel_r4theme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/main.cpp, slot1launch/bootloader/source/main.arm9.c, slot1launch/bootloaderAlt/source/hook.c, slot1launch/bootloaderAlt/source/main.arm7.c, title/arm9/source/graphics/FontGraphic.cpp, title/arm9/source/main.cpp, title/arm9/source/nand/sector0.c
Silence warnings
I played Pokémon Gold on a dsi theme using bootstrap on 3DS flashcart.
***
=> Silence warnings

romsel_dsimenutheme/arm9/source/esrbSplash.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, title/arm9/source/main.cpp, universal/include/common/logging.h, universal/source/common/logging.cpp
Updated logPrint function with variable argument support.
This allows a file to be accessed once instead of multiple times.
***
I have checked that the same log is output as before.
***
=> Refactor logPrint function to use variable arguments

quickmenu/arm7/source/main.c, quickmenu/arm9/source/main.cpp
After a minor refactoring before pushing the previous commit I forgot to revert this local change of mine
***
=> Fix wrong parameter passed to backlight fifo in previous commit

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- Improved the dropdown animation in the DSi theme to resemble a bit more the _actual_ DSi Menu, creating smoother visuals.
This new animation takes gravity and restitution into account, resulting in a much nicer effect. However, it still does not look 100% like the original, since it's hard to figure out the correct values to use without messing up the timing. It's close, though!
**Before:**
**After:**
melonDS 0.9.5
Nintendo DSi XL UTL-001(USA) with Unlaunch
***
=> Improved Dropdown Anim (DSi Theme)

quickmenu/arm9/source/graphics/fontHandler.cpp, quickmenu/arm9/source/graphics/graphics.cpp, quickmenu/nitrofiles/languages/en/language.ini
This PR cleans up some of the code of #2397. This also:
- Fixes minor oversights;
- Changes the name of variables to be a bit more descriptive.
Nintendo DSi XL with Unlaunch
melonDS 0.9.5
=> Code cleanup for Clock & Calendar

romsel_aktheme/arm9/source/fileBrowse.cpp
The file list scrolls when the cursor passes half of the visible entries, except this time I fixed the previous issues which caused the cursor to go off the screen when D-Left, D-Right, or SELECT keys were pressed.
I recompiled and tested this twice to make sure there weren't any other mistakes. (For real this time.)
=> Better scrolling (without messing up stuff)

README.md
I know it's such an insignificant change, but man, it's been bothering me for a while.
I hope Stewmath appreciates it.
=> Update 'Drenn' to 'Stewmath' in README.md
