DS-Homebrew/TWiLightMenu

.vscode/settings.json, README.md, booter/compile_docker.ps1, booter_fc/compile_docker.ps1, compile_docker.ps1, docker/Dockerfile, romsel_dsimenutheme/compile_docker.ps1, romsel_r4theme/compile_docker.ps1, rungame/compile_docker.ps1, titleandsettings/compile_docker.ps1
This is a companion pull request to issue #145. While it does not fix the issue, it provides a workaround by including a working Docker image of a build environment compatible with DSiMenu++.
It is almost impossible to acquire an installation devkitARM r47, this is by design on part of the devkitPro contributors. The current supported revision is devkitARM r49, which is not compatible with DSiMenu++. 
This pull request introduces a way to build DSiMenu++ using Docker and a Linux image with devkitARM r47, libnds 1.7.1, and EasyGL2D preinstalled as a workaround until DSiMenu++ can be updated to support devkitARM r49.
5.4.0.1 built with this image works identically to the release binaries on a hardware DSi and New 3DS, as well as NO$GBA. Build scripts were tested on Windows 10 build 17778. …
=> Add a Dockerfile & helper scripts to build on a working environment of devkitARM r47.

romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, titleandsettings/arm9/source/soundeffect.h
* Disallowed going up the folder hierarchy if `showDirectories` is false
* Initialized sound effect state variables in titleandsettings to prevent odd sound bugs.
Nintendo DS with Unlaunch 1.3
*** 
=> Fix some small akmenu bugs.

titleandsettings/nitrofiles/languages/english.ini, titleandsettings/nitrofiles/languages/french.ini, titleandsettings/nitrofiles/languages/german.ini, titleandsettings/nitrofiles/languages/italian.ini, titleandsettings/nitrofiles/languages/japanese.ini, titleandsettings/nitrofiles/languages/spanish.ini
Remove outdated description for certain icons appearing white when turning on animated DSi-enhanced icon as this is already fixed as of v.5.2.0
=> Remove outdated description for DESCRIPTION_ANIMATEDSIICONS_1

7zfile/DSiWare (JAP)/Nintendo DSi Sound (J).launcharg
Added launcharg file for Nintendo DSi Sound on Japanese consoles
On my Japanese DSi with Unlaunch 1.3, Hiya 1.3.2, and TWiLight 6.4.1
*** 
(I don't know how to build stuff ^, but it's just a launcharg file and it works)
=> Add Japanese Nintendo DSi Sound launcharg

titleandsettings/arm9/source/settingsgui.cpp, titleandsettings/arm9/source/settingsgui.h
Now the app should autmatically split the settings in the top screen.
I couldn't test it because all my builds failed, and i couldn't properly configure docker on my pc, so i don't even know if it works as intended
*** 
=> setTopText auto splits strings

romsel_aktheme/arm9/source/common/pergamesettings.cpp, romsel_aktheme/arm9/source/common/pergamesettings.h, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp
This adds choosing which nds-bootstrap version (release or nightly) you want to use to per game settings on the Acekard theme.
I'm not sure if you actually want to add this, but if you do it's nice to be able to choose nightly for non_blocking_io on just games that work better with it without having to go into settings every time.
If you want I can try add this to the other themes, but the acekard theme is the only one I can compile...
On my DSi (J) with the latest Hiya/Unlaunch/TWiLight
*** 
=> Acekard theme: Add per game bootstrap choosing

settings/nitrofiles/languages/spanish.ini
_Removed the "_1" after the "DESCRIPTION" string, and the | symbol._
*** 
=> Deleted "_1" and | symbol

romsel_aktheme/arm9/source/windows/mainlist.cpp
Make the Acekard theme hide the `saves` folder too
My DSi (JPN), with latest Unlaunch/HiyaCFW/TWiLight
*** 
(using RocketRobz libnds fork)
=> Acekard theme: Hide `saves` folder from being shown

romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp
Saving to the ini file was out of order, so everything saved to the wrong values. This fixes that.
EDIT (2<sup>nd</sup> commit): Now this also fixes the compact list view causing a guru error by loading in the rom icons, but not drawing them on screen. (Fixes #261)
DSi (J) latest TWiLight / HiyaCFW / Unlaunch
*** 
=> Acekard theme: Fix per-game settings windows & list view causing guru error (Fixes #261)

romsel_aktheme/arm9/source/windows/rominfownd.cpp
The Acekard theme wasn't saving the `Bootstrap File` option in per-game settings, now it does
DSi (J) with latest HiyaCFW / TWiLight / Unlaunch
*** 
=> Acekard theme: Fix not saving hb rom's bootstrap file

romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_aktheme/arm9/source/common/bootstrapconfig.h, romsel_aktheme/arm9/source/systemfilenames.h, romsel_aktheme/arm9/source/windows/calendar.cpp, romsel_aktheme/arm9/source/windows/calendar.h, romsel_aktheme/arm9/source/windows/calendar_2.cpp, romsel_aktheme/arm9/source/windows/calendar_2.h, romsel_aktheme/arm9/source/windows/cheatwnd.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.h, romsel_aktheme/arm9/source/windows/rominfownd.cpp, romsel_aktheme/arm9/source/windows/rominfownd.h, romsel_aktheme/nitrofiles/language/lang_cn/language.txt, romsel_aktheme/nitrofiles/language/lang_de/language.txt, romsel_aktheme/nitrofiles/language/lang_en/language.txt, romsel_aktheme/nitrofiles/language/lang_es/language.txt, romsel_aktheme/nitrofiles/language/lang_fr/language.txt, romsel_aktheme/nitrofiles/language/lang_it/language.txt, romsel_aktheme/nitrofiles/language/lang_jp/language.txt, romsel_aktheme/nitrofiles/language/lang_ko/language.txt, romsel_aktheme/nitrofiles/language/lang_zh/language.txt
- Place a `usrcheat.dat` file in `sd:/_nds/TWiLightMenu/akmenu/cheats/`, then press `Y` on a game to open its settings, then press `X` to select which cheats you want to use.
- Add the file `calendar/weekday_text.bmp` to your theme folder, then add the following (with your own x/y values) to `uisettings.ini`:
```
[calendar weekday]
x = 155
y = 20
show = 1
```
- You can use a second weekday if you want too, for that you need `calendar/weekday_text_2.bmp` in your theme folder and this (w/ correct x/y) in `uisettings.ini`:
```
[calendar weekday 2]
x = 3
y = 3
show = 1
```
- *Note:* `calendar/weekday_text.bmp` and `calendar/weekday_text_2.bmp` should contain all of the days, each exactly 1/7th the height of the height of the file going `Sunday → Saturday` (top → bottom)
On my DSi (J) with the …
=> Acekard theme: Reimplement the cheat UI and add the ability to show the day of the week

booter/Makefile, rungame/Makefile
<sub>*but might break something else</sub>
This makes it so `booter` and `rungame` compile for me on the latest devkitPro, devkitARM, (RocketRobz) libnds, ect. but I'm not sure if doing this breaks anything, `booter` seems fine for me (but I can't test on Windows), but while `rungame` compiles, it doesn't actually seem to work (but I don't have access to SDNAND menu so I can't launch it w/ Hiya).
If this doesn't break the apps (especially `rungame`) or break anything on windows this at least means `booter` compiles successfully, but **it should be tested on windows and for `rungame` on a system that can normally compile it**.
- Mac running 10.14.2 with the latest dkp and dka, with the RocketRobz fork of libnds
- DSi (J) with latest TWiLight, Unlaunch, and HiyaCFW
*** 
_(Do not edit after …
=> Fix compilation errors in booter and rungame*

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp
- Adds a cheat menu to the DSi and 3DS themes
- *Note: This isn't perfectly stable. For some reason despite working fine on the R4 theme I sometimes get Guru Meditation Errors in the DSi/3DS themes, but it usually works fine and I can't figure out how to do it better*
- Updates the R4 theme cheat menu to be `X` in per-game settings to match the other themes
DSi (J) with latest Hiya/TWiLight/Unlaunch
*** 
=> DSi/3DS themes: Add cheat menu, R4 theme: Update cheat menu to open with X in per-game settings

settings/arm9/source/bootstrapsettings.h, settings/arm9/source/main.cpp
Wait for my nds-bootstrap PR too
=> Add support for “Simple Dark” and “Simple Light” loading screens

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- It was setting the randomizer seed after calling generating the number, meaning it would always be the same
DSi (J) with the latest TWiLight, HiyaCFW, and Unlaunch
*** 
=> DSi theme: Set randomizer seed before randomizing

settings/arm9/source/language.cpp
I wrongly added "i +" in the length of the substr, it could have caused issues in the case the next character was a valid hexadecimal digit.
*** 
=> Fixed typo in ReplaceExtASCII

settings/arm9/source/settingsgui.cpp
Fixed an issue where if you scrolled an option backwards, like the languages option, when going from option 0, the result of the modulus wasn't the latest option but -1. With this change, the size of the option list is added so that the result of the modulus is the same, and it doesn't have to deal with negative values.
No$gba
*** 
=> Fixed backwards option scrolling

settings/arm9/source/language.cpp, settings/nitrofiles/languages/italian.ini, settings/nitrofiles/languages/spanish.ini
Instead of using the woakaround from my latest commit, now the loaded text is directly parsed from utf8 encoding to be used by teh current font system.
no$gba
*** 
=> Added proper utf8 parsing function

.travis.yml
This changes the cia directory from (on .travis.yml and TWLBot)
`3DS - CFW users/cia/` to
`3DS - CFW users/`
This change was discussed on the discord server (started by VoltZ and I decided I wanted it like this too)
=> Change cia file directory

settings/arm9/source/language.cpp, settings/arm9/source/main.cpp
This PR has been tested using the provided devkitPro, devkitARM and tested on DSi console.
The chinese.ini Not yet created and translated!Because there is no Chinese characters fonts support
=> Fixed Guru Error when misc setting page if set language to 6 in settings.ini

README.md, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
* Fixes the black artifacts in the 3DS theme
* `playRotatingCubesVideo` now uses asynchronous DMA on a higher-priority channel
* Bottom background (`BG_GFX`) is refreshed on the highest priority channel at the end of the Vblank 
* Not gone completely but greatly reduced.
* Direct`BG_SUB_GFX` access has been replaced with buffered atomic DMA
* Before modifying `BG_SUB_GFX`, call `beginBgSubModify`
* Instead of changing `BG_SUB_GFX` directly, change `bgSubBuffer` instead.
* Call `commitBgSubModify` or `commitBgSubModifyAsync` to write changes to `BG_SUB_GFX`
* This provides a tiny (but noticeable increase) in performance especially with boxart.
Nintendo DSi hardware.
*** 
=> Fix black artifacts in the 3DS theme due to rotating cubes.

Makefile, romsel_dsimenutheme/arm9/source/fileBrowse.cpp
In the DSi theme, now when you are scrolling, box art is not displayed
The start border is not drawn while you are scrolling
As a result, lag when scrolling has been reduced
Small typo in the Makefile has been fixed
Old 2DS
*** 
=> DSi Theme: Reduce scroll lag

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
`photoPath` now only gets assigned if `dirOpen` is set to true. This prevents a bug on flashcarts (at least on my R4) where the DSi menu theme crashes and the DS is powered off.
DS Lite (r4)
Old 2DS (r4 & SD)
*** 
=> Assign photoPath only if dirOpen is true

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.h, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
The corner button palettes on the 3DS theme become corrupt sometimes, especially when changing icon positions. This just reloads the palettes once in a while to stop the corruption.
Nintendo DSi hardware.
*** 
=> dsimenu: Reload the corner button palettes on the 3ds theme

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
=> Clean the select Menu icons when gbar2 bios error

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
Prevent boxart from staying after pressing to scroll past the last game.
If scrolling from a folder in the 3ds theme to nothing, do not call `clearBoxArt()`. Prevents flickering.
Old 2DS (DSi/3DS themes, with directories on/off)
*** 
=> Scroll fixes

romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_aktheme/arm9/source/windows/mainwnd.h
The select handler for the akmenu list view would be called twice if someone clicks the icon, causing a Guru meditation in some cases, and going down two folders in others. This is makes it so it's only called once.
Nintendo DSi hardware
*** 
=> akmenu: Only call select handler once on list click (fixes #415)

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/main.cpp
* Reverted commits that implemented the start border delay
* Tweaked the `keysDownRepeat` delays to mimic the system menu behaviour
* at the same time, `keysDownRepeat` should show that left/right buttons were pressed even if there is some lag for `scanKeys`, thus fixing the start border showing for a split second.
Nintendo DSi Hardware
*** 
=> Fix DSi start border showing for a split second without the use of a delay

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
Accessing `dirContents[scrn].at(...)` when the cursor position was at an empty spot would cause an exception due to out of bounds errors. Since DS homebrew is `noexcept`, this caused the DS to shut down immediately (or quit to an error screen on TWL_FIRM).
This just does bounds checking when a box is tapped to prevent the exception from occurring.
Nintendo DSi Hardware
*** 
=> DSi Theme: Fix shutdown on tapping an empty box.

.travis.yml, compile_docker.sh
Seems like dkA r51 breaks the Travis build. As a workaround, we can use Docker in Travis and build with dkA r50 + patched libnds.
Let's see if this builds properly on Travis before merging...
*** 
=> build: Use docker for travis to workaround dkA r51 incompatibilities

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp
Cheat menu no longer closes after you open it if you hold/press X too long on both the DSi/3DS and R4 themes.
Old 2DS
*** 
=> Fix cheat menu opening/closing rapidly

romsel_dsimenutheme/arm9/source/perGameSettings.cpp
When viewing per game settings in the DSi or 3DS themes, long filenames are truncated to prevent them from being drawn outside of the box. Example: `Patched Mario and Luigi Bowser's In...`.
Old 2DS
*** 
=> 3DS & DSi themes: Truncate long filenames

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
Truncate filename/dirname in delete/hide menu. I forgot to change this in the last PR.
Old 2DS
*** 
=> 3DS & DSi themes: Truncate filename in delete/hide menu

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
This makes the DSi and 3DS themes use the correct icon positions when moving an app.
n3DS (U) with the latest TWiLight.
*** 
=> DSi/3DS themes: Fix icon positions when moving an app

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.h, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
* Reuse a single buffer when loading bottom backgrounds. The buffer is then used for the top texture
* Don't use yet another bmpImgBuffer
* Don't load the bubble tip texture twice
This doesn't quite fix the 4MB problem on 3DS themes yet but hopefully should help get there.
Nintendo DSi Hardware
*** 
=> Reduce memory usage when loading themes

romsel_aktheme/Makefile, romsel_aktheme/arm9/Makefile, romsel_aktheme/arm9/source/common/singleton.h, romsel_dsimenutheme/Makefile, romsel_dsimenutheme/arm9/Makefile, romsel_dsimenutheme/arm9/source/common/singleton.h, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp
C++17 features have been replaced with C++14 workarounds for `dsimenu` and `akmenu`. `settings` relies heavily on C++17 features so it has not been touched.
Hopefully this will increase compatibility with older toolchains (at little to no cost).
*** 
=> DSiMenu/akMenu Remove dependency on C++17

romsel_dsimenutheme/arm9/source/perGameSettings.cpp
* When truncating the filename, makes a copy of the filename before truncating so as to not mutate the actual filename.
This fixes cheats not being loaded on the DSi Theme
Nintendo DSi
*** 
=> DSi/3DS Theme: Don't modify the actual filename when truncating

romsel_dsimenutheme/arm9/source/common/singleton.h, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/Texture.cpp, romsel_dsimenutheme/arm9/source/graphics/Texture.h, romsel_dsimenutheme/arm9/source/graphics/iconHandler.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/resources/dsimenu_theme_examples/theming.md
Loading compressed textures used to use negative fseek. This did not work in some versions of libsysbase, causing corrupt data to be read into the texture buffers, and thus white screens.
This PR also gets rid of some unnecessary heap allocations and uses the `nothrow` version of new for singletons.
NO$GBA, Nintendo DSi, Nintendo DS Lite (thanks @FlameKat53)
*** 
=> Don't use negative fseek.

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
* Only clear the box art if the video was playing before
*** 
=> 3DS Theme: Fix the flicker when going between games with boxarts

azure-pipelines.yml, booter/Makefile, docker/Dockerfile, rungame/Makefile
Fixes booter and LRR cias on TWLbot. Thanks to @Elaugaufein from Discord for investigating.
Confirmed working on n3DS.
=> azure-pipelines: Make make_cia deterministic with the commit ID and restore the ROM icon banner

azure-pipelines.yml, booter/Makefile, docker/Dockerfile, rungame/Makefile
Touch on 3DS doesn't work with the latest nightly booter CIAs. It might have something to do with the SRL header not being patched properly?
=>  Renable manual SRL header patching for booter/rungame.

.vscode/tasks.json, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, settings/arm9/source/language.cpp, settings/arm9/source/language.h, settings/arm9/source/main.cpp, settings/nitrofiles/languages/english.ini
- This adds the ability to sort games by file type
- It sorts alphabetically by file extension, then alphabetically by file name within an extension
- This resolves #406 
DSi (J) with the latest TWiLight / Hiya / Unlaunch.
*** 
=> DSi/3DS Themes: Add file type sorting (Fixes: #406)

manual/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- This improves the momentum in the DSi/3DS themes and Manual so that it doesn't send you backwards if you flick too fast
DSi (J) with the latest Hiya/TWLMenu/Unlaunch
***
=> Improve scrolling momentum with fast flicks

romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp
* Disabled going back from the top level folder in akmenu
* Fill the stream buffer during fadeout/fadein in dsimenu to mitigate missed fills
Nintendo DS Lite
***
=> Small bugfixes

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/sound.cpp, romsel_dsimenutheme/arm9/source/streamingaudio.c, romsel_dsimenutheme/arm9/source/streamingaudio.h
This reverts changes made to fileBrowse.cpp in commit 6723aa57f5b3d93f6c7fc9f1fccac9b8cc869820.
Should hopefully fix lockup issues.
> **Stack3r - Solar Boy Django** Yesterday at 11:58 PM
So I just had the dsimenu theme lock up upon loading the rom selection, the audio was stuck repeating the same note over again and I couldn’t scroll or anything, I had to exit with the home button
***
=> Revert fileBrowse.cpp "Small bugfixes (#540)"

azure-pipelines.yml
This makes Azure do
```
git clone --depth 1 https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
```
instead of
```
git clone https://$GITHUB_TOKEN@github.com/TWLBot/Builds.git
```
which should make the clone significantly faster.
I tried cloning with `--depth 1` it it seemed to work, I think it should work fine on Azure, but haven't tested.
***
=> Do a shallow clone to speed up TWLBot Commit

mainmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
Adds support for the "R4(DS) - Revolution for DS (v2)" flashcart. Unfortunately the cart does not support autoboot AFAIK, but this will allow it to run nds-bootstrap.
R4iSDHC on DSi
***
=> Support for R4iSDHC

mainmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_aktheme/arm9/source/systemfilenames.h, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
- This makes all of the themes and the quick menu write their enabled cheats to the 32kb (`0x8000` bytes) file `sd:/_nds/nds-bootstrap/cheatData.bin`
DSi (J) with the latest Unlaunch and TWiLight Menu++
***
=> Write enabled cheats to 'cheatData.bin'

README.md, mainmenu/arm9/source/cheat.cpp, mainmenu/arm9/source/cheat.h, mainmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.h, romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.h, romsel_r4theme/arm9/source/main.cpp
- This makes `cheatData.bin` have `u32` values instead of simply writing the text.
DSi (J) with latest TWiLight and Unlaunch
***
=> Use `u32`s in `cheatData.bin` instead of just writing the text

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.h
- This improves the DSi/3DS/R4 Theme's cheat menu's scrolling to have the selected entry not always be the top one.
- The selected entry is now indicated by being indented instead of an `=`
DSi (J) with the latest Unlaunch + TWiLight
***
=> DSi/3DS/R4 Themes: Improve scrolling in cheat menu

mainmenu/arm9/source/graphics/graphics.cpp, mainmenu/arm9/source/main.cpp
- Use feedback on memory optimization from my other PR
- Cleaner ifs statement
- since rom types 1-8 always have the same code regarding wifi, DSiWare & homebrew, just check for the ROM type itself rather than repeat the code a bunch
- Cleanup the emulator code.
No where. This should work the way it is
***
=> [Main Menu] Code cleanup

romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_aktheme/arm9/source/tool/stringtool.cpp, romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/main.cpp
* Fixed a potential memory bug in `ReplaceAll` in both DSiMenu and AKmenu
* Remove need to allocate buffer when creating save files in DSiMenu and AKmenu
* Fixes crash in AKMenu if no save is found.
Nintendo DSi.
Only tested save-creation logic on AKMenu, since current DSiMenu master seems to have an unrelated bug where the ROM folder and ROM path aren't being set correctly (dkA r53), so I can't launch games through DSiMenu.
***
=> Fix crash in akmenu if no save is found

rungame/arm9/source/flashcard.cpp, settings/arm9/source/common/flashcard.cpp, title/arm9/source/common/flashcard.cpp
Allows TWiLightMenu to recognize an Acekart 2i for direct access when Deep Labyrinth is set as it's banner. I prefer the Deep Labyrinth patch over the ones currently available because it works on DSi Firmware 1.4.4 and Horzes (which also supports 1.4.4) causes noticeably longer boot times when running the flashcard normally compared to Deep Labyrinth - for me at least.
Tried running on my DSi through Unlaunch - worked fine (though #699 still causes issues for me - unrelated to this PR however)
***
=> Add direct access support for Acekard 2i with the banner of Deep Labyrinth

azure-pipelines.yml
- This makes the release `.7z` files not have the files in a `TWiLightMenu` folder
- It also makes releases not have docker builds attached
No where ;P
***
=> Don't put files in TWiLightMenu folder for release

quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
- This makes it so that `sd:/_gba/bios.bin` is also a valid location for the GBA bios to match with the latest GBARunner2.
DSi (J) with the latest TWiLight, Unlanch, and GBARunner2
***
=> Check for GBA BIOS in sd:/_gba/

romsel_aktheme/arm9/source/common/tonccpy.c, romsel_aktheme/arm9/source/common/tonccpy.h, romsel_aktheme/arm9/source/dsrom.cpp, romsel_aktheme/arm9/source/dsrom.h, romsel_aktheme/arm9/source/gamecode.h, romsel_aktheme/arm9/source/time/datetime.cpp, romsel_aktheme/arm9/source/tool/dbgtool.h, romsel_aktheme/arm9/source/ui/listview.cpp, romsel_aktheme/arm9/source/ui/listview.h, romsel_aktheme/arm9/source/userinput.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.cpp, romsel_aktheme/arm9/source/windows/dsiiconsequence.cpp, romsel_aktheme/arm9/source/windows/dsiiconsequence.h, romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/mainlist.h, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp
* Switched to `tonccpy`/`toncset` for most usages of `memcpy`/`memset`
* Fix out of bounds dereference in cheat menu when selected index is 0 (fixes crash when pressing left on cheat menu)
* Only allocate space for `tDSiAnimatedBanner` if needed, and not for every `DSRomInfo` (hopefully fixes crashes when enumerating the root SD/SLOT-1 Flashcart directories multiple times)
* Only set up extname filter once (reduces allocations on `enterDir`)
* Rewrite `listview.cpp` row insertion code to be append only and make heavy use of move constructors to prevent unnecessary copies (hopefully fixes crashes when enumerating the root SD/SLOT-1 Flashcart directories multiple times)
* Changed key repeat delays to `(25, 2)` to be inline with DSi Theme
* Nintendo DSi (Unlaunch 1.3)
* Nintendo DS Lite
***
=> Fix Acekard Theme Bugs

romsel_aktheme/arm9/source/dsrom.cpp, romsel_aktheme/arm9/source/dsrom.h, romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp
* Properly copies DSi Animated Icon data in copy constructor
* Reduces size of `DSRomInfo` class to 952 bytes by discarding unused title strings when caching
=> More Acekard Theme Fixes

romsel_aktheme/arm9/source/dsrom.h
* just reorders the struct from largest to smallest for packing reasons
=> akmenu: reorder tNDSCompactedBanner members to pack better

romsel_aktheme/arm9/source/main.cpp, romsel_aktheme/arm9/source/systemfilenames.cpp, romsel_aktheme/arm9/source/systemfilenames.h, romsel_aktheme/arm9/source/ui/listview.cpp, romsel_aktheme/arm9/source/ui/listview.h, romsel_aktheme/arm9/source/windows/batteryicon.cpp, romsel_aktheme/arm9/source/windows/batteryicon.h, romsel_aktheme/arm9/source/windows/volumeicon.cpp, romsel_aktheme/arm9/source/windows/volumeicon.h
* Properly delay loading of SystemFilenames to fix subthemes not loading
* A change in `listview` caused `sfn` to load earlier than `ms` would, defaulting every theme to zelda.
* Make battery and volume icons only load once
=> Acekard Theme SystemFilenames Fixes

azure-pipelines.yml
Added a "lite" download excluding apfix and widescreen folders, as including them makes the extraction super slow on 3ds
nowhere :ultraXD:, but I'm 99% sure it will work
***
=> add a "lite" download, which excludes the widescreen and apfix folders

romsel_aktheme/arm9/source/dsrom.cpp, romsel_aktheme/arm9/source/windows/mainlist.cpp
* fixes a small bug where garbage data would be copied to the banner struct
=> akmenu: fix corrupt icon when setting unknown banner

romsel_dsimenutheme/arm9/source/cheat.cpp, settings/arm9/source/settingsgui.cpp
- Fixes the romsel_dsimenutheme themes crashing when viewing some cheat descriptions
- Also fixes the positioning of the version number in settings
DSi (K) with the latest TWiLight Menu++ / Unlaunch
***
=> Fix cheat description crash

quickmenu/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp
- This makes the box art use the actual size of the image its drawing instead of a preset for that type of rom
- Any size from 0x0 to 256x192 should work and bigger are ignored (though you don't really want to go larger than the user photo picture)
- Both cache and non-cache modes are working for me (DSi), however I can't test on flashcard
DSi (K) with latest TWiLight & Unlaunch.
Video: (Spirit Tracks is 100x100, Heart Gold is 256x192, ホワイト is 258x192 (too big, so skipped))
***
=> Use actual image size instead of preset sizes for box art

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp
My code for the alternate sorting options (recent and custom, most played is alright) and hiding kinda really sucked, I guess I didn't realize ini supported vectors (though json would be better still, but I'm not going to add that unless the whole app was going to switch to it) so I rewrote those so that now the recent and custom use a vector to store the items and it should be more stable or at least *way* cleaner and the hidden games now just do Linux style and stick a `.` in front of the name to hide something.
This will make it no longer able to read the previous recent, custom, and hidden lists, but its much better code
I also fixed recent making it get confused by setting the cursor to the first non-directory before it was done launching, but I wasn't able to get it to do that while …
=> Make the sorting options suck less

manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.h, quickmenu/arm9/source/graphics/FontGraphic.cpp, quickmenu/arm9/source/graphics/FontGraphic.h, quickmenu/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/buttontext.h, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp
- This adds proper UTF-8 handling to the DSi-based, and R4 themes, quickmenu, and manual so that files with non ASCII names will show correctly. (If the font actually has the characters)
- Also changes the rom name conversion to convert to UTF-8 instead of hacky UTF-16 so that still works
- Fixes #814 
DSi (J) with the latest TWiLight and Unlaunch.
***
=> Add proper UTF-8 handling

romsel_aktheme/arm9/source/windows/mainlist.cpp, romsel_aktheme/arm9/source/windows/rominfownd.cpp, romsel_aktheme/nitrofiles/language/lang_en/language.txt, romsel_aktheme/nitrofiles/language/lang_jp/language.txt
- I believe every used string in the ak menu should be translated with this
- I also added a few strings to English that were missing
- And made the mainlist strings translatable on the code side
- And updated the Direct Boot to only use "Direct Boot" as a title with the options "Default", "Off", and "On"
- I removed some unused strings from Japanese and English, but I didn't touch other languages and only removed unused strings from the areas I added to, I didn't remove other unused strings
- (I cared about changing English since if we add crowdin or so English will be the base and will need to contain every string)
- DSi (K) with the latest TWiLight & Unlaunch
- DS Lite (J) with the latest TWiLight & DSTT
***
=> Update Japanese translation (ak theme)

manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.h, quickmenu/arm9/source/graphics/FontGraphic.cpp, quickmenu/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h
- Invalid UTF-8 character (Such as the usrcheat.dat's EUC_JP) will now be replaced by ?? instead of freezing
- I may add conversion from EUC_JP to UTF-8 later for the cheats, that'll be annoying though so not gonna do it now
- DSi (K) with the latest TWiLight & Unlaunch
***
=> Don't freeze on invalid UTF-8 characters

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- This makes the DSi theme use the photo's size so that photos up to 208 x 156 can all load correctly
- It will center smaller ones with a black border
- I could add scaling down / cropping, but there's probably not enough RAM for much bigger images anyways
- I also ran VS Code's convert to tabs and trim trailing whitespace on the file since it was bothering me and tabs were the main indentation of the file
-  Example of default at half scale ~~with a red smiley face I accidentally undid the mouth on~~:
- no$gba v3.0 (It should work on console, but I don't have a µSD adapter on me)
***
=> Correctly load photos less than 208 x 156

Makefile, azure-pipelines.yml
- This simply changes `make package` to directly put `BOOT.NDS` in `DSi&3DS - SD card users` instead of relying on Azure to move it to the correct location which was only being done for releases.
- It puts the files in the correct locations on macOS 10.14, not tested on console since no code was changed.
***
=> Put BOOT.NDS file in correct location in nightlies

quickmenu/arm7/source/main.c, quickmenu/arm9/source/common/dsimenusettings.cpp, quickmenu/arm9/source/main.cpp
_Now copy dlp and pictochat from Nand should works fine on all region/version of DSi console._
_Also use twlCfg for getGuilanguage._
_I tested it on my DSi console._
*** 
=> DS Classic Menu: Fix copy dlp/pictochat from Nand

quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/language.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/language.cpp, settings/arm9/source/common/dsimenusettings.cpp
_Use PersonalData instead of twlCfg for setTitleLanguage._
_And use twlCfg for getGuiLanguage on settings/dsimenu._
_Also disable copy dlp/pictochat from Nand on dev console._
_I tested it on my DSi console._
*** 
=> Use PersonalData for setTitleLanguage

title/arm9/source/main.cpp
_Fix Guru error when boot via some DSiWareHax (or only Memory Pit?)._
_Tested it on my DSi console._
*** 
=> Fix Guru error when boot via Memory pit

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.cpp
- This adds pressing `L` to deselect all cheats (like the Acekard theme)
- I also added `keysSetRepeat(25, 5)` to slow down the scrolling in the cheat menu to an easier to control speed
- **I didn't add text yet since its already got as much as can fit in the box without overflowing...**
- Let me know if you want me to do something for this and what you think would work well there
- ~~why didn't I do this earlier its super easy~~
***
=> DSi/3DS/Saturn/R4: Add deselect all cheats with L

settings/arm9/source/settingsgui.cpp
- This changes the settings scroller (on the right) to be based on the selection's position within that pages total items so that it will be at the bottom only when on the last item and the top only when on the first instead of simply mirroring the left cursor since it seems rather redundant to have both show the same thing
- *<sub>Wasn't sure if I should just add this to my other PR right now but their on completely different topics so I didn't</sub>*
***
=> Make settings scroller based on the total position

romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.h, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, settings/arm9/source/common/dsimenusettings.cpp, settings/arm9/source/common/dsimenusettings.h, settings/arm9/source/language.inl, settings/arm9/source/main.cpp
Fixes #1031
Deletion/hiding of ROMS can now be disabled.
Note this __does__ work on all themes except the R4 and Wood UI themes.
DSi
***
=> DSi Theme: Allow preventing hiding/deleting ROMs

azure-pipelines.yml
- This is just a simple fix that the nightly lite 7z's still had their widescreen files due to some non-escaped spaces
- bash v2.3.57 on macOS 10.14.6 (The copy worked, no code changes so no need to test on DS)
***
=> Fix non-escaped spaces in widescreen from lite 7z

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp
- This makes per game settings use keysDownRepeat for Up/Down/Left/Right so you can just hold to go through several items
- Fixes #955 (NightScript said vertical only, but I did horizontal too because some options have a lot that way too
- Also makes the Saturn theme's "Location: X" string's Y position vary with the if this freezes message above incase a translation needed three lines
***
=> DSi-based/R4: Repeat keys in per game settings

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.h
- I was completely missing an easy solution to this that doesn't seem to have a major speed downside (Just copy the text directly to the main buffer instead of an 8bpp buffer first) until chyyran pointed it out 🤦‍♀️
- Also makes the DSi themes' cheat menu show 8 entries again since that works now
- DS Lite (J) with DSTT and the latest TWiLight
***
=> DSi/Settings: Make text overlapping work

.github/workflows/build.yml
- This makes themes be included in full nightlies, since the lite builds exist if you want a faster install and they have been changing recently
- Untested, but its just a CI change
***
=> Include themes in full nighties

.github/workflows/build.yml
- This adds generating separate 7z's for DSi, 3DS, and Flashcards to hopefully reduce confusion when installing
- The old `TWiLightMenu.7z` (and `TWiLightMenu-Lite.7z` for nightlies) will still be generated exactly as it was so automatic tools won't break
- Also fixes `master` not being pushed resulting in all the TWLBot commits having a tag but not being assigned to any branch
- I think this should fix #918 
- Let me know if y'all have any suggestions for the 7z names, layout, etc.
- On my fork, see an example release at Epicpkmn11/TWiLightMenu [vTEST.37](https://github.com/Epicpkmn11/TWiLightMenu/releases/tag/vTEST.37) and a nightly at TWLBot/Builds [v20200726-002526](https://github.com/TWLBot/Builds/releases/tag/v20200726-002526)
***
=> Make separate 7z's for DSi, 3DS, and FC

booter/Makefile
Quick directory fix in the /booter Makefile. Original line would point to just the upper-level directory instead of /7zfile.
N/A (not necessary for such a change)
***
=> Directory typo fix

.github/workflows/nightly.yml, .github/workflows/release.yml, Makefile, booter/Makefile, booter_fc/Makefile, manual/Makefile, quickmenu/Makefile, rebooter_fc/Makefile, romsel_aktheme/Makefile, romsel_dsimenutheme/Makefile, romsel_r4theme/Makefile, rungame/Makefile, settings/Makefile, slot1launch/Makefile, title/Makefile
This PR:
- Moves the debug files from the main 7z files to their own special 7z files that only go to TWLBot/Builds commits
- Nighties to [`TWiLightMenu-debug.7z`](https://github.com/TWLBot/Builds/blob/master/TWiLightMenu-debug.7z), releases to [`TWiLightMenu-debug-release.7z`](https://github.com/TWLBot/Builds/blob/master/TWiLightMenu-debug-release.7z) (these are from the Actions runs linked below)
- This makes the 7z's about 8MB smaller
- `make package` and some `make dist`s weren't working repeatedly / were changing non-ignored files, as that's the way I prefer to build TWiLight I've cleaned those up so that `make package` and all `make dist`s work nicely
- Deletes Acekard files in the pipeline instead of the Makefile
- Always does `mkdir -p`
- Also just cleaned up the `""` a bit, I …
=> Cleanup make dist / package & move debug files from 7z's

title/arm9/source/graphics/gif.cpp
- This just changes the limit to pre-decompress GIFs to 256KiB in DS Mode instead of 1MiB, I did a bit of testing and GIFs were crashing well before hitting 1MiB when pre-decompressing so this lets larger GIFs work in DS Mode
- DSi (K) with latest Unlaunch
- DSi (K) with DSTT direct booting TWiLight Menu++
***
=> Lower pre-decompression limit to 512KiB in DS mode

slot1launch/arm9/source/launch_engine.c, title/arm9/source/main.cpp
Possibly fixes booting DS browser as well, and others that may require the quick altBootloader workaround in the future.
Closes #1215 
[In my standalone fork](https://github.com/unresolvedsymbol/TWLM_NTR_Launcher)
DSi XL (DSiWare)
DSi XL (DSTWO Flashcart)
***
=> Various fixes: DSTWO, Flashcart themes

settings/arm9/source/language.inl, settings/arm9/source/main.cpp, settings/nitrofiles/languages/english.ini
- As noticed by @vargaviktor on Crowdin, it's `Magenta`, not `Magneta` ;P
- N/A
***
=> Fix typo in settings

romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.h, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/language.inl, romsel_dsimenutheme/nitrofiles/languages/english.ini, romsel_r4theme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/main.cpp
This makes it show a warning when launching anything on an SD card that isn't 32KB clusters. If you'd prefer I could change it to only show for DS games as I don't think the others (except maybe GBA?) are impacted much/at all as they don't read from SD much, but I figure it's best to just show it whenever as even TWiLight itself is slower on smaller clusters. I made it dismissible permanently with X in case for whatever reason you can't format to 32KB clusters.
Edit: Oh yeah, added to DSi-based and R4-based themes, so everything currently usable except the quick menu.
- DSi (K) with the internal SD, DSTT, Acekard 2i, and Datel Game n' Music, all (except GNM) with both a 32KB clusters card and an 8KB clusters card
***
=> Show warning when launching on non 32KB clusters

.github/workflows/release.yml
- For who knows why adding this .ignoreme file helped avoid libarchive bugginess, but as that has finally been fixed for real in Universal-Updater, this is no longer needed
- N/A
***
=> Don't make .ignoreme files

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
Moves the DMA copy for color debanding to the end of the VBlank handler, I couldn't get it to freeze with this where it was freezing a lot for me before. I honestly see no difference at all between it on and off besides being a lot slower to load the boxart when on so not sure if this doesn't work as well? No one said anything on Discord so I'm assuming this is more stable at least, though tbh I think just removing the debanding would be a better solution.
- DSi (K) from internal SD and Acekard 2i
***
=> Move DMA copy for debanding to the end of VBlank

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h
So this is way easier than I was imagining it to be, just print substrings. It's not the smoothest ever, but looks plenty fine. It waits for 1 second after moving and scrolls 1 char per 10th of a second, then waits for 2 seconds on hitting either end.
https://user-images.githubusercontent.com/41608708/103437379-aeaefa00-4bec-11eb-91f3-dd526ff0169f.mp4
- The R4 theme just dies if I tell it to print a substr though so gotta figure that out lol
- Fixes #1239 
- DSi (K) from internal SD
***
=> DSi themes: Scroll selected item in cheat list

settings/arm9/source/language.inl, settings/nitrofiles/languages/english.ini
- TWiLight typically uses American spellings, even the Nintendo logo color is ["Gray"](https://github.com/DS-Homebrew/TWiLightMenu/blob/master/settings/nitrofiles/languages/english.ini#L230), so I think it's kinda odd that this uses the British spelling
- N/A
***
=> Change "Greyscale" to "Grayscale"

manual/arm9/source/main.cpp, quickmenu/arm9/Makefile, quickmenu/arm9/source/graphics/FontGraphic.cpp, quickmenu/arm9/source/graphics/FontGraphic.h, quickmenu/arm9/source/main.cpp, rebooter_fc/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/Makefile, romsel_r4theme/arm9/source/graphics/FontGraphic.cpp, romsel_r4theme/arm9/source/graphics/FontGraphic.h, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/Makefile, rungame/arm9/source/main.cpp, settings/arm9/Makefile, settings/arm9/source/common/cardlaunch.h, settings/arm9/source/main.cpp, slot1launch/cardengine_arm7/source/cardEngine.c, title/arm9/Makefile, title/arm9/source/common/cardlaunch.h, title/arm9/source/main.cpp
Unlaunch expects DSiWare file names in UCS-2, not just UTF-8 with every other byte null, so this fixes that by properly converting the file names.
- DSi (K) from internal SD, not from flashcard as I've not been able to get the secondary device stuff working
***
=> Fix non-ASCII file name DSiWare with Unlaunch

quickmenu/arm9/source/cheat.cpp, quickmenu/arm9/source/cheat.h, quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/common/bootstrapconfig.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.cpp, romsel_aktheme/arm9/source/windows/cheatwnd.h, romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/cheat.h, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.h, romsel_r4theme/arm9/source/graphics/graphics.cpp, romsel_r4theme/arm9/source/main.cpp
- I noticed this was using fstreams which adds ~300KB to the binary for no reason, so this just switches to normal `FILE *`s, saving like 1MB between all the places it was used
- Also makes it not convert from u32 to string and back for no reason
- DSi (K) from internal SD with DSi and R4 themes and the DS classic menu, the Acekard theme did compile past the cheats but then hit errors elsewhere and it's disabled anyways so it's not tested, I did update it though
***
=> Don't use fstream for cheat writing

.gitignore, manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/graphics.cpp, manual/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.cpp
- Fixes the manual text using the wrong palette and it glitching on page load
- Fixes #1302 
- For some reason the freezing seems to have been caused by expanding the image vector and I couldn't get it to work properly while expanding so I just made it so that you can't scroll all the way onto the top screen
- Also fixes text being able to print 1 char past the edge of the screen in all places using the new text rendering
- DSi (K) from internal SD and Acekard 2i
***
=> Fix manual text and glitching on page load

quickmenu/arm9/source/common/dsimenusettings.cpp, quickmenu/arm9/source/common/dsimenusettings.h, quickmenu/arm9/source/graphics/graphics.cpp, quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/common/dsimenusettings.cpp, romsel_aktheme/arm9/source/common/dsimenusettings.h, romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.h, romsel_r4theme/arm9/source/graphics/fontHandler.cpp, romsel_r4theme/arm9/source/graphics/graphics.cpp, romsel_r4theme/arm9/source/main.cpp, settings/arm9/source/common/dsimenusettings.cpp, settings/arm9/source/common/dsimenusettings.h, settings/arm9/source/main.cpp, settings/arm9/source/settingspage.h, title/arm9/source/common/dsimenusettings.cpp, title/arm9/source/common/dsimenusettings.h
- Makes macOS's annoying `._` files not be shown in the fonts, skins, etc lists in settings
- Also a bit of other minor things that I felt like cleaning up but shouldn't actually have any affect on usage
- Makes the fonts, gba borders, and unlaunch background options use `Option::Nul` instead of having some unused subtheme leftovers in there
- To make this work, made Option::Nul return a selection of `0` instead of `-1` so it actually shows the label if there is one, shouldn't break anything if there isn't I don't think
- Fixes the Wreturn-type warning in settings by using else on Option::Nul since that's the only warning in all of settings and there's only those four types so it shouldn't break anything
- Removes everything related to the `subtheme` setting and the already unused …
=> Don't show ._ files in the settings lists and a bit of other minor cleanup

booter/Makefile, title/arm9/source/bootsplash.cpp, title/arm9/source/graphics/gif.hpp
- Fixes the second frame of the touch the touch screen to continue gif sometimes being shown before pausing (notable on English without the H&S, I never noticed because the Japanese gifs weren't doing it)
- Makes START always skip the splash, regardless of if it's done or not. The other buttons all still behave the same and will resume from the user input flag without skipping
- Also fixes the booter Makefile being weird due to having the elf's in `.PHONY`, as noticed by urmum_69 on Discord
- DSi (K) from internal SD and DSTT
***
=> Fix 2nd frame of tttstc being shown sometimes and make START always skip the splash

manual/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.cpp
For some reason I made punctuation at the end of a line after LTR be ignored when it should be processed in RTL
- no$gba
***
=> Fix punctuation after LTR at end of line

manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/language.cpp, settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.h, settings/arm9/source/language.cpp
=> Add RLM and LRM support

manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/language.cpp, settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.h, settings/arm9/source/language.cpp
- So it turns out that numbers are weak (doesn't affect direction) ***b u t*** the numbers *are* LTR, so they need special handling
- It was also missing the last weak char if that was the only char left
- And Crowdin was being dumb with `&lrm;` and `&rlm;` because some flavors of ini (not ours) say that `;` is a comment, so it was quoting the string... but our ini parser doesn't support quoted strings, so I've just removed the `;`s so the new escapes are just `&lrm` and `&rlm`
- DSi (K) from internal SD and no$gba
***
=> Even more bidi fixes!

manual/arm9/source/main.cpp
- This just make it sort the manual pages such that `index.gif` is the first page instead of relying on an early character (`_howToUse.gif`) since this way is much nicer on the web side and just cleaner in general imo
- no$gba
***
=> Show index.gif as first manual page

README.md, booter_fc/Makefile, gbapatcher/Makefile, manual/Makefile, quickmenu/Makefile, rebooter_fc/Makefile, romsel_aktheme/Makefile, romsel_dsimenutheme/Makefile, romsel_r4theme/Makefile, rungame/Makefile, settings/Makefile, slot1launch/Makefile, title/Makefile
- This just updates the README a little bit to have more detailed info on how to build TWiLight Menu++ and to link to the manual
- It also fixes most of the Makefiles not creating `../7zfile/debug` which would cause `make dist` to fail
- N/A
***
=> Expand compiling info and link to manual in README

.github/workflows/nightly.yml
- Somehow I messed up the git command I guess so it was `%b` instead of `%B` so none of the TWLBot releases has messages, this fixes that
- https://github.com/TWLBot/Builds/releases/tag/v20210314-053726
- https://github.com/Epicpkmn11/TWiLightMenu/runs/2105238648
***
=> Fix TWLBot releases not having messages

booter_fc/Makefile
YSMenu, when using the LRABXY soft reset combo, automatically loads whatever is TTMenu.dat. For most other carts, this is fine, however, for r4isdhc.com cards and others using the Autoboot files for that same folder, either TTMenu.dat doesn't exist, or, if YSMenu was extracted, will be YSmenu instead. This would cause the SR to not load the menu, but to load the same game again, since when using YSmenu as a backend, it will load the file listed in AUTO_BOOT.
To fix this, the makefile in booter_fc now copies a DLDI patched BOOT.NDS to a new TTMenu.dat in the r4isdhc.com cards folder. Now when using LRABXY to SR when using YSMenu to load games, it will automatically load TWLMenu++ instead, as that is what that reset combo was intended as (resetting back to …
=> allow YSMenu to SR to TWLMenu using r4isdhc.com cards

quickmenu/arm9/source/main.cpp, romsel_aktheme/arm9/source/windows/mainwnd.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
- Looks like only some of the AP fix and widescreen folder making were given safety checks so the others are still causing crashes, this should fix that
- Fixed it for Nadia on Discord
***
=> Add missing safety checks

romsel_dsimenutheme/arm9/source/language.inl, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_dsimenutheme/nitrofiles/languages/en/language.ini
- Makes the region names translatable
- (don't bother remaking v20.0.1 for this, there won't actually be any translations yet anyways)
- no$gba
***
=> Make region names translatable

settings/nitrofiles/languages/en/language.ini
- `DESCRIPTION_CARDREADDMA` was missing from the English `language.ini` so it's not on Crowdin, this simply adds it to the ini
- no$gba
***
=> Add DESCRIPTION_CARDREADDMA to English ini

.github/workflows/nightly.yml
Since the only thing the nightly lite does now is remove skins and you don't really need those in nightlies anyways there isn't much reason for it to exist anymore now that the pck files are a thing.
Also removes the fonts as they're quite large and don't update often.
- This PR, check the Checks tab once it runs
***
=> Remove nightly lite and don't put skins or fonts in nightly

settings/nitrofiles/languages/en/language.ini
- Accidentally had the ini hotkey strings formatted wrong, this simply fixes that
- N/A
***
=> Derp fix hotkey strings in ini

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- Re-enables the manual icon in the SELECT menu, I could never get the corruption in the first place though so please test this to see if it's fixed itself by now or I'm just lucky
- Closes #1023
- DSi (K) from internal SD, DSTT, Acekard 2i, and Datel Games n' Music (Acekard 2i and Datel Games n' Music were on older version)
***
=> Re-enable manual icon in SELECT menu

quickmenu/arm9/source/iconTitle.cpp, romsel_aktheme/arm9/source/common/fixedbanners.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/iconTitle.cpp
_Check reserved area before loadFixedBanner (If animated banner is good, the unused reserved2 area should be all zerofilled)_
_Tested it on DSi console (except akmenu theme)_
***
- [√] This PR has been tested using the latest version of devkitARM and libnds.
=> Skip loadFixedBanner if rom's animated banner is good

.gitignore, booter_fc/Makefile
Fixes this: https://github.com/DS-Homebrew/TWiLightMenu/issues/1283
DLDI driver has been changed from boyakkey's DLDI to TTCARDIOLibrary.dldi. This allows all SD sizes to boot.
R4i-Gold.com V1.4.1, DSTT, R4i3D.com original
***
=> Fix DSTT & Clones failing to boot with only 2GB SD

booter_fc/Makefile
Running make clean yeets Original R4 / M3 Simply autoboot file.
Solution: found the issue in booter_fc/makefile, and commented it out. If you want me to completely delete it I can do that.
uh WSL2? 
***
=> make clean deletes Original R4 / M3 Simply autoboot files for no reason

.gitignore
#1413 adds a new file to 7zfile which isn't added to gitignore, so I added it. It's a petty change, but it was getting annoying.
WSL2 Ubuntu 20.04
***
=> Add R4i-SDHC TTMENU.DAT to gitignore

manual/arm9/source/graphics/gif.hpp, title/arm9/source/graphics/gif.hpp
- Was causing problems since apparently `size_t` isn't included properly in some cases and it's not actually used
- macOS with latest devkitARM and such
***
=> Remove unused dataSize variable

.gitignore, booter_fc/Makefile
Because #1490 works, that means we can add autoboot files for Ace3DS+ and Ace3DS X using a different encryption key, thanks to the updated `r4denc`.
_Tell us where you've tested it._
Ace3DS+
***
=> Add Ace3DS+ autoboot

booter_fc/Makefile
I did an oopsie in #1490 and #1491. It should now create a folder for each autoboot file whereas it didn't previously. ~~I blame the gitignore, the thing is confusing~~
_Tell us where you've tested it._
WSL2 Ubuntu 20.04
***
=> Fix issue where the booter_fc makefile doesn't create a folder for new autoboots

.gitignore
The Makefile for booter_fc created a new file that wasn't ignored.
Well, now it is.
_Tell us where you've tested it._
Ubuntu 20.04 WSL2
***
=> Update gitignore to match booter_fc Makefile update

title/arm9/source/language.inl, title/arm9/source/main.cpp, title/nitrofiles/languages/en/language.ini
Makes the language/region selector translatable (would you like it if something asked you 英語を話します？はい／いいえ ;P)
It reloads the language every time the GUI option is changed so it should be pretty easy to find your language even if it starts on one that isn't it. Maybe we should add hardcoded strings on the top screen for the official 8 languages or so, I'll need translations in them first though.
- DSi (K) from Unlaunch and DSONE and no$gba
***
=> Make language/region select translatable

title/arm9/source/language.inl, title/arm9/source/main.cpp, title/nitrofiles/languages/en/language.ini
- Makes the reset settings prompt translatable, am I missing anything else in title?
- Also adds French, German, Italian, and Chinese strings for top screen language select
- And makes the line spacing slightly larger in the language and region selects
- DSi (K) from Unlaunch and DSONE and no$gba
***
=> Make reset settings prompt translatable

title/arm9/source/common/dsimenusettings.cpp, title/arm9/source/common/dsimenusettings.h, title/arm9/source/language.cpp, title/arm9/source/language.h, title/arm9/source/main.cpp
- I accidentally broke the reset settings prompt so the settings weren't being reloaded if deleted, so this fixes that
- It also makes newlines in the title work since the English one is already quite tight
- no$gba, DSi (K) from Unlaunch
***
=> Fix reset not reloading settings & allow newlines in its title

manual/arm9/source/graphics/FontGraphic.cpp, manual/arm9/source/graphics/FontGraphic.h, manual/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/graphics/FontGraphic.h, settings/arm9/source/graphics/fontHandler.cpp, title/arm9/source/graphics/FontGraphic.cpp, title/arm9/source/graphics/FontGraphic.h, title/arm9/source/graphics/fontHandler.cpp, title/arm9/source/main.cpp
- Reads from the file to a buffer, then tonccpys that to the expansion pak, I think the problem was that fread() was doing 8-bit writes
- Also a fair bit of cleanup such as using pointers to not have a partly initialized font, using `new` buffers instead of vectors, and moving lastUsedLoc into the class, but nothing that should impact functionality
- DSi (K) from Unlaunch and DSONE
- DS Lite (J) from DSONE
***
=> Fix font being buggy when loaded to Memory Expansion Pak

booter/Makefile
- Makes booter.nds be repacked with the animated banner
- ndstool corrupts it when using `-t twl_banner.bin` directly, but for whatever reason it works when repacking
- DSi (K) in TWiLight and n3DS (U) in HOME Menu
***
=> Repack booter with animated banner

romsel_dsimenutheme/arm9/source/main.cpp, settings/arm9/source/main.cpp
- Fixes the DS mode username in the DSi theme sometimes picking up garbage leftovers from old names at the end
- The username has the length specified right after it and I guess sometimes when using a shorter name it doesn't actually overwrite the end to null so that'll show up if you just show all 10
- Also removes settings printing the name to the top screen when FAT init fails as that seems unnecessary and was doing the length wrong there too, if there's a reason that's done let me know and I can undo it
- Tested by @SNBeast (I'm not having the issue)
***
=> Fix DS mode username

quickmenu/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp
=> Fix getTitleLanguage() returning gameLangauge

quickmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/source/main.cpp
Fixes #1447.
~~I think I covered everything~~ At any point a ROM is to be loaded with nds-bootstrap turned off on a DSONE SDHC or DSONEi, it should now load it through YSMenu.
**Only works on DSONE SDHC and DSONEi. YSMenu is incompatible with the original DSONE.** And, as far as I'm aware, the current autoboot doesn't work on the original DSONE anyway.
2x DSONE SDHC. 
***
=> Use YSMenu as flashcart loader for DSONE(i) SDHC

quickmenu/arm9/source/errorScreen.cpp
- Sorry, didn't notice this was missed in the last commit until checking VS Code again after it was merged :sweat_smile:
- Simply fixes the error screen text palette so the text is actually visible
***
=> Fix DS Classic Menu error screen palette

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
Makes the DSi theme show a random nds-bootstrap screenshot on the top screen if there are no photos in `sd:/_nds/TWiLightMenu/dsimenu/photos`.
- DSi (K) from Unlaunch and DSONE
***
=> DSi theme: Display bootstrap screenshot on top if no photos

universal/include/asyncReadExcludeMap.h
- They freeze with black screens when trying to play videos (on loading levels) with it on
- LEGO Star Wars: The Complete Saga and LEGO Indiana Jones: The Original Adventures work fine with async, I don't have any other LEGO games to test though
- Sorry if I messed something up, haven't touched these lists before lol
***
=> Add LEGO Harry Potter games to async exclude list

.github/workflows/nightly.yml
- Actions is so fun
- I forgot it uses the 7z files again in the next step so this changes back to copying them instead of moving them
- The apfix.pck worked at least
- Haven't...
***
=> Copy 7z files instead of moving

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp
- I accidentally broke the spacing in #1578, this fixes it
- Also makes it move smoothly and fixed up the spacing in general bit more which is why this took a while. The spacing should be pixel perfect to the real DSi menu now I think, the movement isn't quite the same but this was a bit easier and looks at least as good imo.
https://user-images.githubusercontent.com/41608708/128965353-044cfbe1-993f-4af1-b4a7-98119d8d6d0c.mp4
- DSi (K) from Unlaunch, no$gba
***
=> Fix spacing of game icons in DSi-based themes

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- Fixes the scrollbar not allowing you to select the last item
- Also extends the touch area to right up against the left/right buttons instead of just the bips area
***
=> Fix scrollbar not allowing you to select the last item

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/fileBrowse.h, romsel_r4theme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/main.cpp
- Speeds up directory loading a bit, I think it cuts the directory load time about in half, but game info loading is only slightly improved
- A folder with 300 copies of BOOT.NDS goes from 8s to 4.5s for me
- My DS ROM folder goes from 2s to 1.5s for me
- The main slow part now is checking if files are hidden, with hidden files shown it's only about 1.5s for any folder with 40+ items for me
- Also updates the R4 theme extension() function
***
=> Speed up directory loading a bit

manual/arm9/source/graphics/gif.hpp, title/arm9/source/graphics/gif.hpp
- This fixes instantly skipping the splash if you have only one GIF that loops infinitely
***
=> Fix instantly finishing for single infinite GIF

romsel_r4theme/arm9/source/main.cpp
- Fixes the R4 theme loading the language before the settings, resulting in resetting the bootstrap in-game menu to the system language
- Fixes #1630
***
=> Fix R4 theme loading language before settings

.gitignore, booter_fc/Makefile, quickmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/source/main.cpp
M3 DS Real can now use YSMenu as flashcart loader.
DLDI submodule was also updated to include the DLDI driver required `booter_fc` to be compiled as YSMenu's soft-reset target.
M3 DS Real, DS phat.
***
Some notes to consider:
- This will only work when also using the provided Autoboot, or by loading TWiLight from YSMenu directly.
- I could not think of another way to avoid accidentally having any other cart using the "M3DS" DLDI name launch YSMenu. The DLDI name must match either the one used in TWiLight Menu++, or YSMenu.
- Also, the original M3 DS DLDI does not work on TWiLight Menu++ anyway. The DLDI has a 32KB section and TWiLight Menu++ expects 16KB or less.
- A workaround for this is to, well, not use the original M3 DS DLDI when launching TWiLight using the official kernel. This …
=> Allow M3 DS Real to use YSMenu as flashcart loader

quickmenu/arm9/source/common/dsimenusettings.cpp, romsel_aktheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/source/main.cpp, settings/arm9/source/common/dsimenusettings.cpp, title/arm9/source/common/dsimenusettings.cpp
Please comment on this PR if anyone disagrees with this change. I think it makes much more sense to have them on as imo removing the flashcard blacklist, region locks, and RSA checks is generally worth losing the sound and splash, I don't even mind it removing those.
Ofc having it as an option is good, I just don't see why we should disable that fairly useful Unlaunch feature by default.
- N/A
***
=> Default Unlaunch's launcher patches to on

booter_fc/Makefile, booter_fc/flashcart_specifics/R4iLS/arm7/Makefile
Apparently the Ace3DS+ and clones (R4iLS-related, and Gateway Blue) does not like the arm7 iwram. It appeared to have broken as of this commit: https://github.com/DS-Homebrew/TWiLightMenu/commit/bfa8e3024401b59e0300ccf8cabe5d6097176cb3
Made a flashcart-specific again, this time using the regular specs for arm7 only. The arm9 works fine as-is.
theSpaceHero#8783: Ace3DS+
@lifehackerhansol: r4isdhc.com.cn PLUS, DSi XL
***
=> Use regular arm7 specs for Ace3DS+ and co.

settings/arm9/source/settingsgui.cpp
- cca1069c85764dec282348e3a373b67fb79fd7c7 changes to printing with small, but still calculates the size using the large font, this makes it calculate the size using the small font so it still warps correctly
- Even german doesn't have anything overflow now
- no$gba
***
=> Calculate settings descriptions with small font

quickmenu/arm9/source/common/dsimenusettings.cpp, quickmenu/arm9/source/common/dsimenusettings.h, quickmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.cpp, romsel_dsimenutheme/arm9/source/common/dsimenusettings.h, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/main.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp, rungame/arm9/source/main.cpp, slot1launch/arm9/source/main.cpp, title/arm9/source/common/dsimenusettings.cpp, title/arm9/source/common/dsimenusettings.h, title/arm9/source/main.cpp
- Makes it so that blacklisted settings are just completely hidden from per-game settings and ignored if an old value was set
- Can be disabled by setting `IGNORE_BLACKLISTS` to `1` in `settings.ini`, this is intentionally not added into the settings menu so that it won't be turned on by people who don't know what they're doing
***
=> Hide blacklisted settings from per-game settings

romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp
- Fixes blacklists causing the blacklisted options to be hidden for all games until a reboot
- Fixes #1707
***
=> Fix blacklists hiding options until reboot

.gitignore, booter_fc/Makefile
Added autoboot payloads for R4iTT 3DS based clone flashcarts. At the moment only the ones specified in the folder name are tested, but that much should be obvious.
R4i3D 2012, r4isdhc.com Silver RTS Lite NEW, DS Lite
***
=> autoboot: support R4iTT 3DS based clones

booter_fc/Makefile, quickmenu/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp, rungame/arm9/source/main.cpp, title/arm9/source/main.cpp
The DLDI that was initially used for the M3 DS Real autoboot (taken from YSMenu) is slower than the official M3 DS Real DLDI provided from Sakura. This has now been updated to use the faster DLDI as it turns out it fits in the max 16KB space.
There appears to be some actual improvements to B4DS performance, but I've only tested NFSU2 so far.
M3 DS Real, DS Lite
***
=> Use faster DLDI for M3 DS Real

universal/sdmmc/arm7/source/my_sdmmc.c
Fixes the SD inserted check so that it shows the FAT init failed screen instead of hanging on white screens forever if booted without an SD card.
- DSi (K) from wifiboot and DSi (U) from SysNAND DSi Menu
***
=> Fix SD inserted check

booter_fc/arm7/source/main.c, booter_fc/arm9/source/main.cpp
This PR:
- Fixes #1735
- Does the `isRegularDS` check on arm7 and passes it to arm9 as the arm7 requires this distinction now. This could probably be done by using different FIFO values.
DSONE SDHC, DS Lite
DSONE SDHC, DSi XL / Unlaunch
***
=> Fix booter_fc poweroff fail on DS

manual/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, settings/arm9/source/graphics/fontHandler.cpp, title/arm9/source/graphics/fontHandler.cpp
- Uses the small font for all text if there's a custom small font but no custom large font
- Allows for more glyphs in the small font since there's more RAM available due to only having one font loaded
- Fixes #1781 
***
=> Use only small font if no custom large font

.github/workflows/release.yml, romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- Noticed that making the `icons` folder wasn't added to the release.yml in #1800 so this adds that
- Also fixed a minor bug I noticed where it would fail to load the icon if it was one of the games that showed up immedietly on load (instead of scrolling over to it/entering a folder)
- DSi LL (J) from Unlaunch
***
=> Make icons dir in release builds & bug fix

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp
- Allows for animated custom icons and custom titles
- Same place as PNGs, but with `.bin` instead of `.png`
- DSi LL (J) from Unlaunch
***
=> Allow using a banner.bin as a custom icon

quickmenu/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/iconTitle.cpp
Small bug fix to the custom icon PNG conversion code to stop it from adding extra green to all the colors.
***
=> Whoops I added too much green to custom icons

Dockerfile, booter/Makefile, patch_ndsheader_dsiware.py, resources/Makefile, rungame/Makefile
- Fixes `patch_ndsheader_dsiware.py` in Python 3 (2 still works) and updates the Makefiles to use python3 if found
- Updates the Dockerfile to use the latest, same as Actions
- macOS 10.15, can't test docker
***
=> Add support for Python 3, update Dockerfile

settings/nitrofiles/languages/en/language.ini
- Accidentally left the `Emulation/HB settings` string instead of the `Games and Apps settings` string
- Fixes #1829
***
=> Derp fix, restore Games and Apps settings string

quickmenu/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/iconTitle.cpp
- Allows using any PNG up to 32x32 instead of just specifically 32x32 for custom icons
***
=> Allow custom icons under 32x32

universal/include/twlClockExcludeMap.h
The Rune Factory games have been added to the TWL clock speed exclude map, according to reports from Lillie and the nds-bootstrap compatibility list.
Only the exclusion map has been updated, and the game(s) have been tested with 67MHz and 133MHz.
- With this PR, [nds-bootstrap/1030](https://github.com/DS-Homebrew/nds-bootstrap/issues/1030) can be closed
- While only the first and second games have been found to have issues with TWL clock speed, and no reports have been given regarding the third game, it is logical that the third game is also affected
***
=> Add Rune Factory games to TWL clock speed exclude list

quickmenu/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_r4theme/arm9/source/iconTitle.cpp
- When a custom banner PNG was below 32×32 it could leave part a previously loaded icon behind, this fixes that
***
=> Ensure old banner data is always cleared

.github/workflows/nightly.yml
- Fixes the build webhook not being sent on failure
(I'll fix the embed to not have the `v -` in a sec)
- On my fork, Actions is re-disabled though so I can't link the run
***
=> Fix failure webhook not sending

booter/Makefile, gbapatcher/Makefile, manual/Makefile, quickmenu/Makefile, romsel_aktheme/Makefile, romsel_dsimenutheme/Makefile, romsel_r4theme/Makefile, rungame/Makefile, settings/Makefile, slot1launch/Makefile, title/Makefile
- Swaps the 1st and 2nd lines of the banners on everything except booter so that you now have:
> DSi-based themes
> TWiLight Menu++
> Rocket Robz
instead of
> TWiLight Menu++
> DSi-based themes
> Rocket Robz
- This should hopefully reduce confusion in Unlaunch since there will only be one listing called `TWiLight Menu++`, instead of a dozen or so
- Also changed title's from `Main` to `Title Splash`
- Haven't, actions will test building
***
=> Swap 1st and 2nd banner lines

universal/source/common/twlmenusettings.cpp
It causes a lot of graphical issues on the bottom screen in exchange for an improvement to the box art/photos that honestly isn't all that noticeable imo. I'm fine with it staying an option for the people who like it but there's been quite a few people recently concerned about the graphical glitches so imo it'd be better to default to off.
If others have thoughts on this, please comment.
***
=> Default color de-band to off

.github/workflows/nightly.yml
TWLBot/Builds has filled up again and I think the debug files are probably a fairly large part of why it happened so quickly, so this makes them not be uploaded for nightlies as I honestly don't think they've ever been used. Release ELFs are still uploaded as I have used those once or twice.
- Haven't
***
=> Remove debug files from nightlies

.github/workflows/release.yml, settings/arm9/source/main.cpp, settings/arm9/source/settingsgui.h
Bigger part of the changes needed so nds-bootstrap version files stay together with nds-bootstrap nds files.
This should make it possible to not have a TWiLightMenu folder at all if one just uses nds-bootstrap with a forwarder
=> nds-bootstrap version files stay with nds-bootstrap

romsel_dsimenutheme/arm9/source/language.inl, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.h, romsel_dsimenutheme/nitrofiles/languages/en/language.ini, romsel_r4theme/arm9/source/main.cpp, romsel_r4theme/arm9/source/perGameSettings.cpp, romsel_r4theme/arm9/source/perGameSettings.h
- Which settings are shown is only reloaded on closing and opening per-game settings, I think this is how the rest work? Might want to lock them when on Unlaunch though I suppose
- Closes #1724 
- no$gba
***
=> Add DSiWare Booter to per-game settings

.github/workflows/nightly.yml, .github/workflows/release.yml
Paths weren't case-sensitive.
Fixes DS-Homebrew/TWiLightMenu#1881
=> Fix paths in workflows (#1)

booter/Makefile, booter/animatedbannerpatch.py
Actually made the animated banner work.
Only `booter` is patched. There is no need for any other titles to be patched considering they are not meant to be loaded from the DSi/HOME menu. The only other title we may consider patching is Last-run ROM, I guess, but I've left it out for now.
DSi XL, 1.4.5, hiyaCFW 1.4.0, installed via TMFH
New 3DS XL, 11.15.0, Luma3DS 10.3
***
=> Animated banner patch

romsel_dsimenutheme/arm9/source/graphics/iconHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/iconHandler.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/ndsheaderbanner.cpp, romsel_dsimenutheme/arm9/source/ndsheaderbanner.h
- Fixes the DSi-based themes only using palette 0 of DSi icons regardless of what the animation sequence said to use
- I don't think any retail ROMs ever used more than 1 palette, but my new icon for Wordle DS uses this feature and this makes it match the DSi Menu for behaviour (though oddly the 3DS HOME Menu doesn't support this either)
***
=> Fix DSi icon palettes in DSi-based themes

universal/source/common/twlmenusettings.cpp
- Makes it reset the ROM folder to root if the current folder doesn't exist
- Should fix TWiLight failing to save if you were in a folder, delete it, and load a game from root
***
=> Reset ROM folder if missing

booter/Makefile, booter/animatedbannerpatch.py
- total NTR ROM size entry updated
- total TWL ROM size entry updated
- use total ROM size instead of the actual file size
- now actually compatible with patch_ndsheader_dsiware.py. I guess the total size does matter...
- further improvements to overall system stability and other minor adjustments to enhance the user experience
DSi XL, 1.4.5, hiyaCFW / TMFH
New 3DS XL, 11.15.0, Luma3DS 10.3
***
=> booter: improve animated banner patch for other header entries

romsel_dsimenutheme/arm9/source/cheat.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp, romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/TextEntry.cpp, romsel_dsimenutheme/arm9/source/graphics/TextEntry.h, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.h, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/fontHandler.h, romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp
Added 3 additional font palettes for use in the DSi based themes.
FontPaletteTitlebox applies to the game title in the menu.
FontPaletteDialog applies to all pop-up dialog messages (per-game settings, SELECT Menu, etc.).
FontPaletteOverlay is for anything that renders overlaid against the theme's background (the macro mode shoulder buttons, and HBL's "^" pointer.
Anything that doesn't meet the above categories (white loading screens, certain errors, etc.) uses the regular FontPalette.
The original FontPalette also serves as the default for the other palettes if they are not specified in the config file.
***
=> Multiple font palettes for themes

romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/themefilenames.h
DSi-based themes can bundle a font in the `font` directory. This includes the usual small and large fonts and the ds or dsi specific versions. Theme fonts are only used if the user has their font set to "Default".
***
=> Allow themes to bundle a font

romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp
- The nds-bootstrap game manual will now be set if any of `[filename].txt`, `[full TID].txt`, or `[TID first 3].txt` (TID but region free) is found in `sd:/_nds/TWiLightMenu/extras/manuals`, in that order
- imo we shouldn't bundle these in TWiLight, or at least not yet until they've been fixed up and are more presentable, but this allows them to be easily added
- The manuals in twlmenu-extras are still a bit WIP, I'd like to go through at least some of them manually and clean up the ASCII are to 32 columns, with them run through my script the body text and even some more basic are should be prefectly readable, but the more complex art tends to be completely broken
- If we do ever add these to TWiLight itself they should definitely be put in a pack file, though I think in the twlmenu …
=> Add setting nds-bootstrap game manual

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.h, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/arm9/source/perGameSettings.cpp, romsel_dsimenutheme/nitrofiles/themes/dsi/dark/theme.ini, romsel_dsimenutheme/nitrofiles/themes/hbLauncher/default/theme.ini, romsel_dsimenutheme/nitrofiles/themes/saturn/default/theme.ini
- Username, date, and time positions now come from the skin config, their default (DSi/3DS theme) settings are:
```ini
UsernameRenderY=15
UsernameRenderX=28
UsernameRenderXDS=4
DateRenderY=7
DateRenderX=162
TimeRenderY=7
TimeRenderX=200
```
(I'll update the examples in a bit)
- Closes #1903 
- Any setting can now be overridden for macro mode by putting it in a `[MACRO]` section of the ini with the same name
- `MacroTitleboxTextY` and `MacroTitleboxTextW` parsing is kept for compatibility, however all the internal skins have been switched to the new method for those
- Closes #1904 
***
=> Allow skins to set username/date/time X/Y and override settings for macro mode

quickmenu/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/graphics/iconHandler.cpp, title/arm9/source/bootsplash.cpp
Applies grayscale effect to various places in DSi-based themes where it was previously missing:
- Font palette colors
- Fixes a crash that is seemingly caused by certain font colors being used.
- Loading screen progress bar
- nds-bootstrap screenshots
- When reloading icon palettes
- Fixes animated icons that use multiple palettes (i.e. WordleDS) appearing in color.
Additionally:
- Applies grayscale to background graphics for DS Classic Menu
- Fix flickering and corruption on boxart and background in DSi-based themes when both grayscale mode and boxart debanding are enabled.
- Fix transparency on boot splash Nintendo logo when grayscale is enabled.
***
=> Various grayscale color mode fixes

romsel_r4theme/arm9/source/cheat.cpp, romsel_r4theme/arm9/source/cheat.h
- Makes the cheat names scroll in the R4 theme, same as the DSi theme
- Names are not truncated to fit in the box due to limitations in the printing, will fix if/when I redo that
- Fixes #1919
***
=> Scroll cheat names in R4 theme

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp
- Adds support for transparent pixels in the date/time font
- ~~*This was stupidly easy, why didn't I do this 3 years ago*~~
***
=> Fix transparency in date/time font

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp
- Adds support for transparency in the volume/battery icons, same as #1970 for the date/time font
- Also fixes macro mode using top screen background for the date/time font
***
=> Fix transparency in volume/battery icons

quickmenu/arm7/source/main.c, romsel_dsimenutheme/arm7/source/main.c, romsel_r4theme/arm7/source/main.c, title/arm7/source/main.c
- This variable is only used for the DS Lite, as seen by all the functions that use it having a if check for it.
- For whatever reason, we are doing bit ops on it, causing Wood to go crazy trying to parse the value that is now shifted left by 8, and defaults to 0. So just remove any other unneeded ops.
- This fixes #1968.
DS Lite, R4iTT
***
=> Save DS Lite backlight information verbatim to 0x02003000

romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.cpp
Changed the fallback behavior for when `FontPaletteUsername` and `FontPaletteDateTime` are not specified in `theme.ini` to be consistent with the other font palettes, preserving the ability to change them all at once by just setting `FontPalette`.
I didn't, but it should be fine™.
***
=> Change FontPaletteUsername/DateTime fallbacks

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/graphics/themefilenames.h
- Added two optional macro-mode-specific backgrounds: `bottom_macro` and `bottom_moving_macro`.
- Immediately redraw background UI after the background changes in macro mode.
***
=> DSi Theme: Macro-specific backgrounds

settings/arm9/source/gbarunner2settings.cpp, settings/arm9/source/gbarunner2settings.h, settings/arm9/source/main.cpp
Remember the user's preferred display screen for GBARunner2 so that it can be restored after disabling macro mode.
***
=> Remember preferred display screen after macro mode switch

romsel_dsimenutheme/arm9/source/graphics/FontGraphic.h, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp
- Clears the maximum width for the given string instead of just the actual length, fixing leftover pixels when printing smaller characters like `1`
- Fixes #2011 
- no$gba
***
=> Fix residual text when printing small characters with the date time/username fonts

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.h, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/tool/colortool.cpp
- Fix printing garbage data because of unterminated string when the username is 10 characters long.
- Fix FontPaletteUsername/DateTime not being converted when in grayscale mode (my bad, I left a magic number there before).
- Fix transparent text background becoming pure black/solid in grayscale mode (colortool now preserves bit 15).
- Tighten the screen space that is cleared when printing top-screen text.
For that last one, calcWidth() is used again. The width of the previously printed date/time string is stored so that upon next print we can clear only exactly what needs to be cleared. This isn't a full fix for #2015 but it should help alleviate the issue.
***
=> Some top-screen text printing fixes

romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/main.cpp, universal/include/common/twlmenusettings.h, universal/source/common/twlmenusettings.cpp
Adds `BLOCKED_EXTENSIONS` INI-only setting which is a `:` separated list of all extensions to block, ex:
```ini
BLOCKED_EXTENSIONS = .bmp:.png
```
- no$gba
***
=> Add extension blocking INI-only setting

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp, romsel_dsimenutheme/arm9/source/graphics/fontHandler.cpp
- Makes the top screen fonts blend with the background like they used to before the NFTR change, which makes them look a lot better
- Also makes them use color 0 for transparent instead on bit 15 (like all other fonts), not sure why i though that was a good idea
- no$gba
***
=> Restore alpha blending to top screen fonts

universal/include/common/tonccpy.h
- quad8() was bugged for anything besides `0`, since the input was a u8 an input of say `1` would end up with `0x00010001` instead of `0x01010101`
- My Advent of Code 2022 day 14 program, and several other things I've fixed this on in the past but apparently TWiLight's still bugged
***
=> Fix toncset (byte version) not working correctly

README.md
- This attempts to order all of the credits in alphabetical order, with some exceptions:
- Rocket Robz is displayed first in Main Developers
- Multiple people in a single credit is left more or less arbitrary, I moved some things around but it probably doesn't matter much?
- Translations are left alone as they're ordered alphabetically by the language themselves already
- Also moves some things around and corrected some details, honestly can't remember everything & the diff doesn't help much since everything was reordered
- Moves @DieGo367, @lifehackerhansol, and @NightScript370's "Other" contributions to a new credits category, Secondary Developers
- Adds CrocoDS and AmeDS credits
- Other minor edits
No changes to the code have been made.
***
=> Re-order credits and add Secondary Developers credits

settings/arm9/source/graphics/FontGraphic.cpp, settings/arm9/source/language.inl, settings/arm9/source/main.cpp, settings/nitrofiles/languages/en/language.ini
- Makes hotkeys require at least two buttons (single button hotkeys could still be set manually in the INI if really wanted)
- Allows holding <kbd>B</kbd> to cancel and retain the previous hotkey
- Adds text stating as such
- Oh also fixed a couple unrelated warnings, should maybe have committed that separately whoops
- no$gba
***
=> Improve in-game menu hotkey setting menu

romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.cpp, romsel_dsimenutheme/arm9/source/graphics/ThemeConfig.h, romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_dsimenutheme/nitrofiles/themes/hbLauncher/default/theme.ini, romsel_dsimenutheme/nitrofiles/themes/saturn/default/theme.ini
- Makes it so you can make the loading screen dark, like the HBL and Saturn themes, in any skin
***
=> Allow making the loading screen dark

DoNotZeroFillMem.bin, patch_ndsheader_dsiware.py
- This doesn't need to be a file lol, it's just the string `DoNotZeroFillMem`
- Tested building booter, output is identical
***
=> Remove DoNotZeroFillMem.bin

7zfile/Flashcard users/Flashcart Loader/R4i Gold 1.64/_wfwd/globalsettings.ini, 7zfile/Flashcard users/Flashcart Loader/R4iDSN/_wfwd/globalsettings.ini
- Set `rts=1` on flashcarts that need it for RTS. It was missed, so kernel assumed 0.
- Closes #2147 
- R4iDSN
***
- no source code changes
=> Add missed INI setting for RTS-compatible flashcart loaders

romsel_dsimenutheme/arm9/source/graphics/FontGraphic.cpp
Fixes a possible crash that occurs because of the way font loading checks for the next character map.
Details since I found it kind of interesting:
When loading the location of the next character map, a value of 0 is supposed to indicate no further maps exist. The previous code ignores this and just checks if the location given is within the file size. This causes it to jump to the start of the file and treat it like a character map. The "map type" it finds doesn't match any of the 3 existing types, so no additional characters are mapped. Then it checks for the next map location again, and where it reads this from the second time coincidentally lines up with where an NFTR font usually stores its resource size. For most fonts, this value will fail the loop condition and stop, so this bug …
=> Font crash fix: check next location != 0

romsel_dsimenutheme/arm9/source/iconTitle.cpp, romsel_dsimenutheme/arm9/source/iconTitle.h
Argv files retain custom icons and titles instead of having them be overwritten by the app they point to.
***
=> Fix custom icons/banners on argv files

romsel_dsimenutheme/arm9/source/graphics/ThemeTextures.cpp
Prevent text from being drawn outside of the buffer's bounds when certain positions are used in config.ini. Implemented in such a way that you can hide the text completely by drawing it off screen in any direction, or even leave it partially visible at any edge of the screen if you wanted to for some reason.
melonDS 0.9.5
***
=> Add bounds checks for datetime/username font draws

romsel_dsimenutheme/nitrofiles/ESRB.ini
I edited the `ESRB.ini` file to include more entries. (There might be some games added to the list that already have ESRB ratings embedded within the ROM, so let me or Rocket Robz know so they can be removed from the list. We might need to display the ESRB rating no more than just one time.)
I've tested it on my North American New Nintendo 2DS XL running TWiLightMenu++ v25.8.1 (latest release build) via Luma3DS CFW, verifying games I own to show ESRB ratings, some with content descriptors.
***
=> Add ESRB Ratings for more DS games

.github/workflows/nightly.yml
Removes the following from nightly `.7z` files as they're not really that important for nightlies:
- `roms`
- 3DS - CFW users/Games supported with widescreen.txt
- AP-patched games.txt
- snemul.cfg
None of these use that much space, but this allows Universal-Updater to keep its simple 'extract everything' script for nightlies. imo if it's not worth extracting it's not worth downloading.
- Untested, Actions will run on the PR
***
=> Remove unnecessary files from nightly 7Zs

romsel_dsimenutheme/nitrofiles/ESRB.ini
I have edited the `ESRB.ini` file to include more ratings for multiple titles. The list of titles are as follows:
- Ace Attorney Investigations: Miles Edgeworth
- Band Hero
- Cory in the House
- Diner Dash: Sizzle and Serve
- Disney Alice in Wonderland
- Disney Phineas and Ferb: Across the 2nd Dimension
- Disney Phineas and Ferb: Ride Again
- Disney Wizards of Waverly Place: Spellbound
- GHOST TRICK: Phantom Detective
- Guitar Hero: On Tour
- Guitar Hero On Tour: Decades
- Guitar Hero On Tour: Modern Hits
- Line Rider 2: Unbound
- MySims
- MySims Party
- Peggle Dual Shot
- Phineas and Ferb
- Wizards of Waverly Place
All titles, except for the following, reflect their names on the ESRB's online game ratings search:
- Band Hero (as "Band Hero DS" is not reflected on the box art, nor …
=> Add ESRB Ratings for Multiple Titles

3dssplash/arm7/source/main.c, booter_fc/arm7/source/main.c, imageview/arm7/source/main.c, manual/arm7/source/main.c, quickmenu/arm7/source/main.c, romsel_aktheme/arm7/source/arm7status.h, romsel_aktheme/arm7/source/main.c, romsel_aktheme/arm9/source/common/arm7status.h, romsel_aktheme/arm9/source/common/systemdetails.cpp, romsel_dsimenutheme/arm7/source/main.c, romsel_r4theme/arm7/source/main.c, settings/arm7/source/main.c, title/arm7/source/main.c, universal/include/common/arm7status.h, universal/source/common/systemdetails.cpp
libnds defines REG_SNDEXTCNT already: <https://github.com/devkitPro/libnds/blob/6cfbd4494d94a16982b8e7cefb7c63155a3d894b/include/nds/arm7/audio.h#L97>
So let's just use that.
It compiled. Didn't test anything else, given it is the exact same define just renamed.
***
=> treewide: replace SNDEXCNT define with libnds REG_SNDEXTCNT define

slot1launch/arm9/source/main.cpp
cardReadHeader reads 512 bytes which is more than the size of the sNDSHeader struct (352). Add padding to the struct used so that there's enough space to read into.
This caused freezing when using slot1launch on a ds where cart swapping was required
=> Fix buffer overflow in slot1launch

quickmenu/arm9/source/main.cpp
Fix bug where the icon and title of the slot1 cartridge did not load unless it had been launched previously.
***
=> Fix slot1 not loading in DS Classic Menu

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/sound.cpp, romsel_dsimenutheme/nitrofiles/themes/3ds/light/theme.ini
The conditions for playing the startup jingle are now more closely tied to the music setting rather than just using the 3DS theme.
- The jingle plays when `Regular (3DS)` music is set and does not play when `Regular (DSi)` music is set, regardless of theme. (Saturn is still mute)
- When the music is set to `Theme` the jingle will only play if enabled via `theme.ini` (#2071 is also fixed)
- The built-in 3DS theme now enables the jingle in its config (partially addresses #2055)
- HBL theme now plays the HBL music when music is set to `Theme` (it previously used DSi music in this case)
melonDS 0.9.5
***
- I almost added behavior to set `PlayStartupJingle = 1` to be the default when unspecified in 3DS skins, but decided against it for two reasons. It would be a breaking change to pretty much …
=> DSi-based themes: Tweak startup jingle / music conditions

universal/source/common/twlmenusettings.cpp
Closes #2072
Changes the enum so that skins are the default music option.
According to tests by others, it actually breaks #2071. As such, that should get fixed before this gets merged, so this will be a draft PR until then
***
=> Make Skin's the default music option for DSi themes

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
Fixes a crash that occurs in the 3DS Theme where if you press one of the top icons for Pictochat, Download Play, or the Internet Browser and that launch fails (app not found or browser not set) while your cursor is on a folder, TWiLightMenu++ would restart after you pressed A on the error message.
melonDS 0.9.5
3DS
***
=> Fix crash when missing pictochat/dlp/browser and cursor is over a folder

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- Fixed the EXTREMELY fast scrolling in the Saturn theme by adding a small delay of 4 frames each scroll. This also seems to fix #2074;
- Disabled the Saturn error chime playing on edge bumps, which gets annoying really fast.
melonDS 0.9.5
Nintendo DSi XL UTL-001(USA) with Unlaunch
***
=> Added delay to Saturn scrolling & disabled bump chime

settings/arm9/source/settingsgui.cpp, settings/arm9/source/settingspage.h
- Added an indicator to the end of changed options. It disappears after you save your settings.
melonDS 0.9.5
Nintendo DSi XL UTL-001(USA) with Unlaunch
***
=> Add indicator for modified settings

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/sound.cpp, romsel_dsimenutheme/arm9/source/sound.h, settings/arm9/source/settingsgui.cpp
- This PR adds panning to the sound effect that plays when switching pages (for example, the sound is louder on the right speaker when switching to the next page and vice-versa). This applies to all DSi based themes and the Settings Menu.
Nintendo DSi XL with Unlaunch
melonDS 0.9.5
***
=> Add panning to page switch sound effect

romsel_aktheme/arm9/source/fileBrowse.cpp, romsel_aktheme/arm9/source/graphics/graphics.cpp
Hello. Just made some minor changes to the Wood UI, and thought I might as well submit them in case anyone else thinks they are worth keeping.
Changes:
- File list scrolls when the selection passes half of the list rather than the very end.
- Directory path is only displayed if directories are shown. (This is what chyyran did before.)
- Changed list view line width from 11 to 15 to make the file list easier to read. (This is also what chyyran did before.)
This was tested on my half of a DS Lite.
In addition, I also have an alternate 'white' theme which was edited (with very little effort) from the 'black' theme. I could upload this somewhere too if anyone is interested.
=> Wood UI additions

romsel_aktheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp
- Fixed an issue that made the cursor position be misplaced after launching a game when sorting by recently played.
- This PR kind of addresses #2429 by fixing its described issue. However, this does not implement the requested feature of adding an option that forces the cursor position at the beginning.
melonDS 0.9.5
=> Fix cursor position when sorting by recently played upon reboot

romsel_aktheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/main.cpp, romsel_r4theme/arm9/source/fileBrowse.cpp
Fixes #2432: In my previous pull request, I made an oversight that broke game detection when sorting by recently played. This caused the game to launch with incorrect information, such as the wrong game type, region, or AP-patch.
This happened because the app launching code depended on the `CURPOS` variable, and my code modified its value right before the game launched. This led to TWLmenu failing to detect the game properly.
To fix this, the app launching code now uses the variable `cursorPosOnScreen` instead of `CURPOS`. This name matches the one used in _romsel_akmenu_ for consistency.
- Nintendo DSi XL with Unlaunch
- melonDS 0.9.5
=> DSi-Based themes: Fix launching app with wrong info when sorting by recent

romsel_dsimenutheme/arm9/source/graphics/graphics.cpp, romsel_dsimenutheme/arm9/source/main.cpp
- Added more dropdown animations to closely match DSi menu's behaviour. In it, there are 4 dropdown types: Left-to-Right, Right-to-Left, and what I like to call V-Shaped and Inverted V-Shaped (see below). This PR adds these animations for TWLmenu's DSi theme. Also, just like the original, they are randomly picked upon boot.
- While at it, I also cleaned up some of the dropdown code to be more readable and slightly tweaked the old left-to-right animation.
**Left-to-Right**
https://github.com/DS-Homebrew/TWiLightMenu/assets/167481805/0b81ec0f-b22a-444c-813e-ba34590d71e5
**Right-to-Left**
https://github.com/DS-Homebrew/TWiLightMenu/assets/167481805/bdb3a2d7-7de2-4582-83a5-46ad13060263
**V-Shaped**
https://github.com/DS-Homebrew/TWiLightMenu/assets/167481805/eb0680cf-063b-497e-b209-45e82b2d7d3 …
=> DSi Theme: Added more dropdown animations!

romsel_dsimenutheme/arm9/source/fileBrowse.cpp, romsel_dsimenutheme/arm9/source/main.cpp
- Fixes the recently reported issue in #2432.
Some functions used in the app launching code still mistakenly used `CURPOS` instead of `cursorPosOnScreen`, causing problems. This should be the last fix for this... hopefully.
Nintendo DSi XL with Unlaunch
***
=> DSi-Based Themes: Fix recent sort, again

slot1launch/bootloader/source/main.arm7.c
Fixed bootloader of slot1launch not fully clearing RAM when using Debugger DS hardware (which has double the RAM).
This caused issues due to some cartridges expecting said RAM to be cleared.
Tested on retail DSs and Debugger DSs.
Won't change anything for other hardware.
***
=> Fix partial EXRAM clear on debugger hardware

romsel_dsimenutheme/arm7/source/main.c, romsel_dsimenutheme/arm9/source/fileBrowse.cpp
On DSi consoles, changing the brightness via SELECT+VOL keys will prevent the SELECT Menu or DS Classic Menu from opening.
This key combo is detected by checking for a backlight level change while holding SELECT. I'm not sure if there's a better way to detect the volume keys.
***
=> DSi-based Themes: Don't open select menu when changing brightness on DSi

.gitignore, booter_fc/Makefile
I have added autoboot support for the R4 3DS Gold RTS from r4i-gold.com, which is a clone of the PK3DS flashcart.
These flashcarts do not support the normal ttio_sdhc DLDI driver. Therefore once all of the normal DSTT clone autoboot files have been made, I have added a line to DLDI patch `TTMenu.dat` using Boyakkey's DSTT DLDI driver. The `TTMenu.dat` file will then be moved into the cart's autoboot folder, `r4i-gold.com R4 3DS Gold RTS, PK3DS`, as it is the last flashcart in the makefile to require `TTMenu.dat`.
I have also added the cart's autoboot folder to the `.gitignore` file to prevent git from tracking it.
DS Phat with an R4 3DS Gold RTS
***
=> Add autoboot support for R4 3DS Gold RTS and PK3DS

quickmenu/arm9/source/graphics/graphics.cpp
If the current dldi is a slot2 dldi, properly display the right texture as "SLOT 2" entry in the ds quick menu instead of the "no cart inserted" one
Hardware, booting twilight from a supercard
=> Fix wrong bottom cart texture in quickmenu if using SLOT2 flashcart

title/arm9/source/main.cpp
Same change as in https://github.com/DS-Homebrew/nds-bootstrap/pull/1753
=> Explicitly check for the extra ram to be available and working when running off a SuperCard

romsel_dsimenutheme/arm9/source/fileBrowse.cpp
- **3DS Theme:** Fixed a crash that happened when the user tried to launch apps from the top bar (specifically Pictochat, Download Play and Internet Browser) without hovering any icon in the browser.
melonDS 0.9.5
***
=> 3DS Theme: Fix crash when launching apps from top bar on empty selection

slot1launch/bootloader/Makefile, slot1launch/bootloader/source/main.arm7.c, slot1launch/bootloader/source/main.arm9.c
Fixes various setup issues preventing slot1launch from launching DSi games in DSi mode.
In particular:
- Made sure the 0x10 bytes at 0x0380FFC0 are cleared if not launching is DSi mode. These bytes are used by the ARM7 binaries to determine whether the game is launched on a DSi or not. (In particular, it's bit 2 of 0x0380FFC8, I think... Though it may be bit 7, I'd have to check). So having them mismatch ARM9's mode would cause crashes.
- Set __dsimode, the internal libnds register. This is needed to make sure isDSiMode works properly. In particular, that method is used by disableSlot1 and enableSlot1, so not having it set would cause problems (i.e. cartridge reads not working).
- REG_IF is cleared before booting, as turning off and on the slot 1 triggers an interrupt. If not cleared, …
=> Fix DSi Mode related setup

quickmenu/arm9/source/graphics/graphics.cpp
- Fixed an oversight where the topbar date text in languages that uses 6 or more characters for the date format (like German) would overflow the "draw region," causing the first character to not get rendered.
Before:
After:
melonDS 1.0 RC
***
=>  DS Classic Menu: Fix topbar date text not displaying correctly in German
